// ═══════════════════════════════════════════════════════════════════════════
// PedResus Search Index
// Flat array of searchable entries across all 16 tabs.
// Each entry: { id, tab, tabLabel, section, label, keywords, description }
// ═══════════════════════════════════════════════════════════════════════════

export const SEARCH_INDEX = [

  // ─── CALCULATOR TAB ────────────────────────────────────────────────────────
  {
    id: "calc-weight",
    tab: "calculator",
    tabLabel: "Calculator",
    section: "Weight",
    label: "Weight Calculator",
    keywords: ["weight", "kg", "estimate", "broselow", "length", "age"],
    description: "Calculate or estimate patient weight by age, length, or Broselow tape",
  },

  // ─── EQUIPMENT TAB ────────────────────────────────────────────────────────
  {
    id: "eq-reference-table",
    tab: "equipment",
    tabLabel: "Equipments",
    section: "Reference Table",
    label: "Airway Equipment Reference Table",
    keywords: ["ett", "endotracheal", "tube", "size", "depth", "suction", "laryngoscope", "blade", "lma", "ngt", "defib", "defibrillation", "iv access", "airway equipment", "broselow"],
    description: "ETT size & depth, suction Fr, laryngoscope blade, LMA, NGT, IV gauge, defibrillation joules — by weight/age",
  },
  {
    id: "eq-ett",
    tab: "equipment",
    tabLabel: "Equipments",
    section: "Reference Table",
    label: "ETT Size & Depth Formula",
    keywords: ["ett size", "endotracheal tube", "intubation depth", "uncuffed", "cuffed", "oral", "nasal", "age formula"],
    description: "ETT uncuffed: (age÷4)+4 · Cuffed: (age÷4)+3.5 · Depth: (age÷2)+12 cm oral",
  },
  {
    id: "eq-defib",
    tab: "equipment",
    tabLabel: "Equipments",
    section: "Reference Table",
    label: "Defibrillation & Cardioversion",
    keywords: ["defibrillation", "cardioversion", "joules", "shock", "vf", "vt", "arrhythmia", "aed"],
    description: "Defibrillation 4 J/kg (max 10 J/kg / 360 J) · Cardioversion 0.5–1 J/kg",
  },
  {
    id: "eq-difficult-airway",
    tab: "equipment",
    tabLabel: "Equipments",
    section: "Difficult Airway",
    label: "Difficult Airway Prediction (LEMON / MOANS / RODS)",
    keywords: ["difficult airway", "lemon", "moans", "rods", "predict", "mallampati", "micrognathia", "macroglossia", "pierre robin", "treacher collins", "beckwith", "epiglottitis", "croup", "foreign body", "obesity", "mediastinal"],
    description: "AIDAA 2022 — Structural and acquired difficult airway predictors. LEMON/MOANS/RODS mnemonics",
  },
  {
    id: "eq-vortex",
    tab: "equipment",
    tabLabel: "Equipments",
    section: "Difficult Airway",
    label: "Vortex Approach — CICO / Neck Rescue",
    keywords: ["vortex", "cico", "cannot intubate", "cannot oxygenate", "face mask", "sga", "lma", "neck rescue", "efona", "tracheostomy", "cricothyrotomy", "surgical airway", "chrimes", "lifeline"],
    description: "3 lifelines: Face Mask → SGA → ETT → Neck Rescue (eFONA). Optimise each before escalating",
  },
  {
    id: "eq-fob",
    tab: "equipment",
    tabLabel: "Equipments",
    section: "Difficult Airway",
    label: "Fibreoptic Bronchoscope Sizing",
    keywords: ["fibreoptic", "fob", "bronchoscope", "awake intubation", "scope size", "railroading", "ett load", "glycopyrrolate", "antifog", "topical lignocaine"],
    description: "Scope OD by weight: <3 kg 2.2 mm → adolescent 4.9 mm. Load ETT before insertion",
  },
  {
    id: "eq-spo2",
    tab: "equipment",
    tabLabel: "Equipments",
    section: "Monitoring",
    label: "Pulse Oximetry — Limitations & SpO₂ Targets",
    keywords: ["spo2", "pulse oximetry", "saturation", "co poisoning", "methhaemoglobin", "nail polish", "probe site", "preductal", "postductal", "pphn", "limitations"],
    description: "SpO₂ targets, probe sites by age, COHb false normal, MetHb reads ~85%. Pre/post-ductal difference in PPHN",
  },
  {
    id: "eq-bvm",
    tab: "equipment",
    tabLabel: "Equipments",
    section: "Monitoring",
    label: "Bag-Valve-Mask (BVM) Technique",
    keywords: ["bvm", "bag mask", "bag valve", "ec clamp", "jaw thrust", "two person", "mask seal", "opa", "npa", "reservoir", "pop off valve", "ventilation"],
    description: "EC technique, 2-person preferred, jaw thrust, OPA/NPA sizing, tidal volume 6–8 mL/kg",
  },
  {
    id: "eq-bp",
    tab: "equipment",
    tabLabel: "Equipments",
    section: "Monitoring",
    label: "Blood Pressure Cuff Selection",
    keywords: ["blood pressure", "bp cuff", "nibp", "oscillometric", "auscultatory", "doppler", "cuff size", "width", "falsely high", "falsely low"],
    description: "Cuff width = 40% arm circumference. Too small → falsely HIGH. Too large → falsely LOW",
  },

  // ─── VITALS TAB ───────────────────────────────────────────────────────────
  {
    id: "vitals-normal",
    tab: "vitals",
    tabLabel: "Vitals",
    section: "Normal Ranges",
    label: "Normal Vital Signs by Age",
    keywords: ["vitals", "heart rate", "hr", "respiratory rate", "rr", "blood pressure", "sbp", "normal", "age", "neonate", "infant", "toddler", "school", "adolescent"],
    description: "Age-specific normal HR, RR, SBP ranges from neonate to adolescent (PALS 2020)",
  },

  // ─── RESUSCITATION TAB ────────────────────────────────────────────────────
  {
    id: "resus-cpr",
    tab: "resuscitation",
    tabLabel: "Resuscitation",
    section: "CPR",
    label: "Paediatric CPR — 15:2 Ratio",
    keywords: ["cpr", "compressions", "chest compressions", "ratio", "15:2", "2 rescuer", "depth", "rate", "recoil", "ccf", "compression fraction"],
    description: "15:2 ratio, rate 100–120/min, depth ⅓ AP diameter. 2-thumb encircling preferred",
  },
  {
    id: "resus-pulseless",
    tab: "resuscitation",
    tabLabel: "Resuscitation",
    section: "Pulseless Arrest",
    label: "Pulseless Arrest Algorithm (VF/VT/PEA/Asystole)",
    keywords: ["arrest", "pulseless", "vf", "vt", "pea", "asystole", "shockable", "non shockable", "adrenaline", "epinephrine", "amiodarone", "defibrillation", "cardiac arrest"],
    description: "Shockable: VF/pVT — defibrillate 4 J/kg. Non-shockable: PEA/asystole — CPR + adrenaline q3–5 min",
  },
  {
    id: "resus-adrenaline",
    tab: "resuscitation",
    tabLabel: "Resuscitation",
    section: "Drugs",
    label: "Adrenaline (Epinephrine) — Cardiac Arrest",
    keywords: ["adrenaline", "epinephrine", "cardiac arrest", "0.01 mg/kg", "1:10000", "iv", "io", "q3 min"],
    description: "0.01 mg/kg IV/IO (= 0.1 mL/kg of 1:10,000). Repeat every 3–5 min",
  },
  {
    id: "resus-anaphylaxis",
    tab: "resuscitation",
    tabLabel: "Resuscitation",
    section: "Anaphylaxis",
    label: "Anaphylaxis — Adrenaline IM",
    keywords: ["anaphylaxis", "adrenaline im", "epinephrine", "0.01 mg/kg", "1:1000", "anterolateral thigh", "auto-injector", "epipen", "biphasic", "allergy", "urticaria", "angioedema"],
    description: "IM adrenaline 0.01 mg/kg (max 0.5 mg) anterolateral thigh. Repeat q5–15 min. Only life-saving drug",
  },
  {
    id: "resus-svt",
    tab: "resuscitation",
    tabLabel: "Resuscitation",
    section: "Arrhythmia",
    label: "SVT — Adenosine / Cardioversion",
    keywords: ["svt", "supraventricular tachycardia", "adenosine", "cardioversion", "vagal", "valsalva", "ice", "rapid push", "narrow complex", "tachycardia"],
    description: "Adenosine 0.1 mg/kg rapid IV push (max 6 mg), 2nd dose 0.2 mg/kg. Cardioversion 0.5–1 J/kg if unstable",
  },
  {
    id: "resus-bradycardia",
    tab: "resuscitation",
    tabLabel: "Resuscitation",
    section: "Arrhythmia",
    label: "Bradycardia — Atropine / CPR",
    keywords: ["bradycardia", "atropine", "0.02 mg/kg", "slow heart rate", "atrioventricular block", "pacing", "transcutaneous"],
    description: "Atropine 0.02 mg/kg IV (min 0.1 mg, max 0.5 mg). HR <60 + poor perfusion → CPR",
  },
  {
    id: "resus-shock-septic",
    tab: "resuscitation",
    tabLabel: "Resuscitation",
    section: "Shock",
    label: "Septic Shock — Hour-1 Bundle",
    keywords: ["septic shock", "sepsis", "fluid bolus", "antibiotics", "norepinephrine", "noradrenaline", "vasopressor", "lactate", "blood culture", "warm shock", "cold shock", "distributive"],
    description: "20 mL/kg NS bolus, blood cultures before antibiotics, broad-spectrum <1 hr, noradrenaline first-line vasopressor",
  },

  // ─── VENTILATOR TAB ───────────────────────────────────────────────────────
  {
    id: "vent-settings",
    tab: "ventilator",
    tabLabel: "Ventilator",
    section: "Settings",
    label: "Ventilator Settings — Weight-Based",
    keywords: ["ventilator", "vent settings", "tidal volume", "peep", "rate", "rr", "fio2", "pip", "minute ventilation", "ie ratio", "inspiratory time", "prvc", "simv", "pc ac", "vc ac"],
    description: "Vt 6–8 mL/kg, age-appropriate RR, PEEP 5–8 cmH₂O, FiO₂ titrate to SpO₂. Mode recommendations by condition",
  },
  {
    id: "vent-ards",
    tab: "ventilator",
    tabLabel: "Ventilator",
    section: "Settings",
    label: "ARDS Lung Protective Strategy",
    keywords: ["ards", "lung protective", "low tidal volume", "permissive hypercapnia", "plateau pressure", "driving pressure", "peep ladder", "prone", "recruitment manoeuvre", "ardsnet"],
    description: "Vt 4–6 mL/kg IBW · Plateau ≤30 · Driving pressure ≤15 · ARDSnet PEEP-FiO₂ ladder",
  },
  {
    id: "vent-troubleshoot",
    tab: "ventilator",
    tabLabel: "Ventilator",
    section: "Troubleshoot",
    label: "High PIP / Low Vt / Hypoxia — DOPE Mnemonic",
    keywords: ["high pip", "high pressure", "low vt", "dope", "displaced", "obstructed", "pneumothorax", "equipment failure", "stacked breaths", "auto peep", "troubleshoot", "alarm", "bronchospasm", "circuit disconnect"],
    description: "DOPE: Displaced ETT · Obstructed (suction) · Pneumothorax · Equipment failure · Stacked breaths (auto-PEEP)",
  },
  {
    id: "vent-waveforms",
    tab: "ventilator",
    tabLabel: "Ventilator",
    section: "Waveforms",
    label: "Ventilator Waveforms — Live & Library",
    keywords: ["waveforms", "pressure scalar", "flow scalar", "volume scalar", "inspiratory hold", "plateau pressure", "expiratory hold", "auto peep", "shark fin", "flow starvation", "capnography", "etco2"],
    description: "Live waveform simulator + static waveform library. Inspiratory/expiratory hold manoeuvres",
  },
  {
    id: "vent-etco2",
    tab: "ventilator",
    tabLabel: "Ventilator",
    section: "Waveforms",
    label: "EtCO₂ / Capnography",
    keywords: ["etco2", "capnography", "capnogram", "end tidal co2", "rosc", "oesophageal intubation", "rebreathing", "shark fin co2", "curare notch", "cpr monitoring", "phases capnogram"],
    description: "Normal capnogram phases, obstructive shark-fin pattern, oesophageal intubation, ROSC detection via EtCO₂",
  },
  {
    id: "vent-weaning",
    tab: "ventilator",
    tabLabel: "Ventilator",
    section: "Weaning",
    label: "Weaning & Spontaneous Breathing Trial (SBT)",
    keywords: ["weaning", "extubation", "sbt", "spontaneous breathing trial", "cuff leak", "post extubation stridor", "hfnc", "niv", "cpap", "dexamethasone pre extubation", "comfort score"],
    description: "SBT: PS 5–8 cmH₂O + PEEP 5 for 30–120 min. Cuff leak test. Pre-extubation dexamethasone 0.25 mg/kg q6h × 4",
  },

  // ─── FLUIDS TAB ───────────────────────────────────────────────────────────
  {
    id: "fluids-maintenance",
    tab: "fluids",
    tabLabel: "Fluids",
    section: "Maintenance",
    label: "Maintenance Fluid — 4-2-1 Rule",
    keywords: ["maintenance", "4-2-1", "holliday segar", "daily fluid", "mL/hr", "fluid rate"],
    description: "4 mL/kg/hr for first 10 kg + 2 mL/kg/hr for next 10 kg + 1 mL/kg/hr for remainder",
  },
  {
    id: "fluids-bolus",
    tab: "fluids",
    tabLabel: "Fluids",
    section: "Maintenance",
    label: "Resuscitation Fluid Bolus",
    keywords: ["bolus", "resuscitation", "20 mL/kg", "normal saline", "lactated ringer", "shock bolus", "fluid challenge"],
    description: "20 mL/kg isotonic crystalloid (NS/LR) over 5–20 min. Repeat up to 60 mL/kg in first hour",
  },
  {
    id: "fluids-dka",
    tab: "fluids",
    tabLabel: "Fluids",
    section: "DKA",
    label: "DKA Fluid Protocol — 48hr Replacement",
    keywords: ["dka", "diabetic ketoacidosis", "48 hours", "deficit", "cerebral oedema", "insulin infusion", "0.45% nacl", "dextrose switch", "glucose monitoring", "ispad", "iap dka"],
    description: "Deficit over 48 hr (not 24). Insulin 0.05–0.1 units/kg/hr after 1 hr fluids. Cerebral oedema: mannitol or 3% NaCl",
  },
  {
    id: "fluids-dehydration",
    tab: "fluids",
    tabLabel: "Fluids",
    section: "Diarrhoea",
    label: "Dehydration Assessment & ORT (Plan A/B/C)",
    keywords: ["dehydration", "ort", "oral rehydration", "ors", "plan a", "plan b", "plan c", "who imci", "diarrhoea", "sunken eyes", "skin turgor", "fontanelle", "tears"],
    description: "WHO/IAP: Plan A (none), Plan B (ORS 100 mL/kg over 4 hr), Plan C (IV NS 20 mL/kg). Zinc + ORS mandatory",
  },
  {
    id: "fluids-burns",
    tab: "fluids",
    tabLabel: "Fluids",
    section: "Burns",
    label: "Parkland Formula — Burns Fluid",
    keywords: ["parkland", "burns", "tbsa", "lund browder", "first 8 hours", "next 16 hours", "lactated ringer", "maintenance burns", "uo target", "burn fluid"],
    description: "3 mL/kg/%TBSA Hartmann/LR over 24 hr. Half in first 8 hr from burn time. Target UO 1 mL/kg/hr",
  },
  {
    id: "fluids-shock",
    tab: "fluids",
    tabLabel: "Fluids",
    section: "Shock",
    label: "Shock Types & Management",
    keywords: ["shock", "hypovolaemic", "distributive", "cardiogenic", "obstructive", "septic", "anaphylactic", "crt", "capillary refill", "mottling", "vasopressor", "dobutamine", "dopamine", "noradrenaline"],
    description: "Identification, fluid strategy and vasoactive drugs for hypovolaemic, distributive, cardiogenic, obstructive shock",
  },
  {
    id: "fluids-periop",
    tab: "fluids",
    tabLabel: "Fluids",
    section: "Peri-op",
    label: "EBV / Allowable Blood Loss / NPO Deficit",
    keywords: ["ebv", "estimated blood volume", "allowable blood loss", "abl", "npo deficit", "transfusion", "pRBC", "hemoglobin trigger", "perioperative", "surgical"],
    description: "EBV by age-band, ABL formula (EBV × ΔHgb / Hgb̄), NPO deficit (hours × 4-2-1 rate). pRBC trigger Hb <7",
  },

  // ─── ABG TAB ──────────────────────────────────────────────────────────────
  {
    id: "abg-interpreter",
    tab: "abg",
    tabLabel: "ABG",
    section: "Interpreter",
    label: "ABG Step-by-Step Interpretation",
    keywords: ["abg", "arterial blood gas", "ph", "paco2", "hco3", "bicarbonate", "acid base", "acidosis", "alkalosis", "metabolic", "respiratory", "mixed", "winters formula", "compensation"],
    description: "pH → Primary disorder → Compensation (Winters'/formulas) → Anion gap → Delta-delta → A-a gradient",
  },
  {
    id: "abg-anion-gap",
    tab: "abg",
    tabLabel: "ABG",
    section: "Anion Gap",
    label: "Anion Gap & MUDPILES",
    keywords: ["anion gap", "hagma", "nagma", "mudpiles", "methanol", "uraemia", "dka", "lactic acidosis", "ethylene glycol", "salicylates", "iron", "isoniazid", "delta delta"],
    description: "AG = Na − (Cl + HCO₃) · Normal 8–12. HAGMA → MUDPILES differential. Delta-delta ratio for mixed disorders",
  },
  {
    id: "abg-oxygenation",
    tab: "abg",
    tabLabel: "ABG",
    section: "Oxygenation",
    label: "A-a Gradient & Oxygenation",
    keywords: ["a-a gradient", "alveolar arterial", "fio2", "pao2", "vq mismatch", "shunt", "diffusion", "hypoxaemia", "oxygenation", "paediatric normal pao2"],
    description: "A-a gradient = (FiO₂ × 713 − PaCO₂/0.8) − PaO₂. Normal <15 mmHg. Elevated = V/Q mismatch or shunt",
  },

  // ─── DRUGS TAB ────────────────────────────────────────────────────────────
  {
    id: "drugs-resuscitation",
    tab: "drugs",
    tabLabel: "Drugs",
    section: "Drug Doses",
    label: "Resuscitation Drugs (IV) — Weight-Based",
    keywords: ["adrenaline", "atropine", "adenosine", "amiodarone", "naloxone", "calcium gluconate", "calcium chloride", "magnesium sulfate", "sodium bicarbonate", "glucose", "d10w", "resuscitation drugs"],
    description: "Weight-calculated doses for adrenaline, atropine, adenosine, amiodarone, naloxone, Ca gluconate, MgSO₄, NaHCO₃",
  },
  {
    id: "drugs-rsi",
    tab: "drugs",
    tabLabel: "Drugs",
    section: "Drug Doses",
    label: "RSI Drugs — Ketamine, Propofol, Rocuronium, Suxamethonium",
    keywords: ["rsi", "rapid sequence intubation", "ketamine", "propofol", "etomidate", "midazolam", "rocuronium", "suxamethonium", "succinylcholine", "vecuronium", "nmb", "paralytic", "induction"],
    description: "Ketamine 1–2 mg/kg, Propofol 1–2 mg/kg, Rocuronium 1.2 mg/kg, Suxamethonium 2 mg/kg for RSI",
  },
  {
    id: "drugs-anticonvulsant",
    tab: "drugs",
    tabLabel: "Drugs",
    section: "Drug Doses",
    label: "Anticonvulsants — Status Epilepticus Protocol",
    keywords: ["status epilepticus", "seizure", "lorazepam", "midazolam", "diazepam", "levetiracetam", "phenytoin", "fosphenytoin", "phenobarbital", "valproate", "thiopentone", "anticonvulsant", "benzodiazepine"],
    description: "Midazolam IN 0.2 mg/kg → Lorazepam IV 0.1 mg/kg → Levetiracetam 40–60 mg/kg → Midazolam infusion",
  },
  {
    id: "drugs-antibiotics-iv",
    tab: "drugs",
    tabLabel: "Drugs",
    section: "Drug Doses",
    label: "IV Antibiotics — Ceftriaxone, Meropenem, Vancomycin",
    keywords: ["ceftriaxone", "cefotaxime", "meropenem", "vancomycin", "gentamicin", "amikacin", "piperacillin", "pip taz", "teicoplanin", "colistin", "acyclovir", "artesunate", "iv antibiotic"],
    description: "Weight-based IV antibiotic doses: ceftriaxone 50–100 mg/kg, meropenem 20–40 mg/kg, vancomycin 15 mg/kg q6–8h",
  },
  {
    id: "drugs-analgesics",
    tab: "drugs",
    tabLabel: "Drugs",
    section: "Drug Doses",
    label: "Analgesia — Morphine, Fentanyl, Ketamine (sub-dissoc)",
    keywords: ["morphine", "fentanyl", "intranasal fentanyl", "in fentanyl", "ketamine analgesia", "sub dissociative", "ketorolac", "paracetamol iv", "perfalgan", "pain", "analgesia"],
    description: "Fentanyl IN 1.5 mcg/kg, Morphine 0.1 mg/kg, Sub-dissociative Ketamine 0.2–0.5 mg/kg, Ketorolac 0.5 mg/kg",
  },
  {
    id: "drugs-vasoactives",
    tab: "drugs",
    tabLabel: "Drugs",
    section: "Drug Doses",
    label: "Vasoactive Infusions — Dopamine, Noradrenaline, Adrenaline",
    keywords: ["dopamine", "dobutamine", "noradrenaline", "norepinephrine", "adrenaline infusion", "milrinone", "vasopressin", "inotrope", "vasopressor", "infusion", "mcg/kg/min"],
    description: "Dopamine 2–20 mcg/kg/min, Noradrenaline 0.05–1 mcg/kg/min, Adrenaline 0.05–1 mcg/kg/min infusions",
  },
  {
    id: "drugs-neonatal-specific",
    tab: "drugs",
    tabLabel: "Drugs",
    section: "Drug Doses",
    label: "Neonatal Specific — Caffeine, Surfactant, Prostaglandin E1",
    keywords: ["caffeine citrate", "surfactant", "poractant", "beractant", "prostaglandin e1", "alprostadil", "ductus arteriosus", "apnoea prematurity", "vitamin k", "phytomenadione", "neonatal drugs"],
    description: "Caffeine 20 mg/kg load, Surfactant 200 mg/kg ET, PGE1 0.05–0.1 mcg/kg/min to maintain PDA",
  },
  {
    id: "drugs-nebs-salbutamol",
    tab: "drugs",
    tabLabel: "Drugs",
    section: "Nebulised Drugs",
    label: "Salbutamol Nebulised — Asthma / Bronchospasm",
    keywords: ["salbutamol", "albuterol", "nebulised", "bronchodilator", "saba", "asthma", "bronchospasm", "2.5 mg", "5 mg", "mdi", "spacer", "asthalin", "ventolin", "continuous nebulisation"],
    description: "<20 kg: 2.5 mg · ≥20 kg: 5 mg q20 min × 3. MDI+spacer preferred over nebuliser for mild-moderate asthma",
  },
  {
    id: "drugs-nebs-adrenaline",
    tab: "drugs",
    tabLabel: "Drugs",
    section: "Nebulised Drugs",
    label: "Nebulised Adrenaline — Croup / Post-extubation Stridor",
    keywords: ["nebulised adrenaline", "neb adrenaline", "croup", "stridor", "1:1000", "0.5 mL/kg", "rebound stridor", "post extubation", "epiglottitis", "laryngotracheobronchitis"],
    description: "0.5 mL/kg of 1:1000 undiluted (max 5 mL) nebulised. Observe ≥2–4 hr post-dose for rebound stridor",
  },
  {
    id: "drugs-nebs-ipratropium",
    tab: "drugs",
    tabLabel: "Drugs",
    section: "Nebulised Drugs",
    label: "Ipratropium Bromide Nebulised — Moderate-Severe Asthma",
    keywords: ["ipratropium", "sama", "duolin", "ipravent", "moderate asthma", "severe asthma", "anticholinergic", "bronchodilator", "combined", "q20 min"],
    description: "<5 yr: 250 mcg · ≥5 yr: 500 mcg. Add to salbutamol for first 1–2 hr in moderate-severe asthma",
  },
  {
    id: "drugs-nebs-budesonide",
    tab: "drugs",
    tabLabel: "Drugs",
    section: "Nebulised Drugs",
    label: "Budesonide Nebulised — Croup",
    keywords: ["budesonide", "pulmicort", "budecort", "croup", "ics", "corticosteroid", "2 mg", "subglottic oedema", "inhaled steroid"],
    description: "Croup: 2 mg single dose nebulised (= 0.6 mg/kg dexamethasone PO). Use when oral/IM not possible",
  },
  {
    id: "drugs-nebs-spacer",
    tab: "drugs",
    tabLabel: "Drugs",
    section: "Nebulised Drugs",
    label: "Spacer & MDI Technique by Age",
    keywords: ["spacer", "mdi", "inhaler", "aerochamber", "volumatic", "babyhaler", "mask", "mouthpiece", "technique", "breath", "puff", "iap gina"],
    description: "Spacer selection 0–2 yr / 2–6 yr / 6+ yr. MDI+spacer equivalent to nebuliser for mild-moderate asthma",
  },

  // ─── SYRUP CALCULATOR TAB ─────────────────────────────────────────────────
  {
    id: "syrup-amoxicillin",
    tab: "syrup",
    tabLabel: "Syrup Calculator",
    section: "Antibiotic",
    label: "Amoxicillin Syrup — Dose & mL",
    keywords: ["amoxicillin", "novamox", "mox", "amoxil", "syrup", "suspension", "125 mg", "250 mg", "dose", "mL", "aom", "pneumonia", "pharyngitis", "uti"],
    description: "30 mg/kg TDS (max 500 mg). Mox-125 syrup: 25 mg/mL, Mox-250: 50 mg/mL",
  },
  {
    id: "syrup-cefixime",
    tab: "syrup",
    tabLabel: "Syrup Calculator",
    section: "Antibiotic",
    label: "Cefixime Syrup — Dose & mL",
    keywords: ["cefixime", "taxim-o", "zifi", "cefix", "topcef", "syrup", "suspension", "uti", "typhoid", "aom"],
    description: "8 mg/kg/day OD or BD (max 400 mg). Taxim-O 50 susp: 10 mg/mL",
  },
  {
    id: "syrup-azithromycin",
    tab: "syrup",
    tabLabel: "Syrup Calculator",
    section: "Antibiotic",
    label: "Azithromycin Syrup — Dose & mL",
    keywords: ["azithromycin", "azithral", "azee", "zithromax", "syrup", "atypical", "pneumonia", "typhoid", "pertussis", "scrub typhus", "macrolide"],
    description: "10 mg/kg day 1 (max 500 mg) then 5 mg/kg days 2–5. Typhoid: 20 mg/kg OD × 7 days",
  },
  {
    id: "syrup-paracetamol",
    tab: "syrup",
    tabLabel: "Syrup Calculator",
    section: "Analgesic",
    label: "Paracetamol Syrup — Dose & mL",
    keywords: ["paracetamol", "acetaminophen", "calpol", "metacin", "dolo", "syrup", "fever", "pain", "antipyretic", "analgesic", "120 mg", "250 mg"],
    description: "15 mg/kg q4–6h (max 1 g/dose). Calpol-120: 24 mg/mL · Calpol-250: 50 mg/mL",
  },
  {
    id: "syrup-ibuprofen",
    tab: "syrup",
    tabLabel: "Syrup Calculator",
    section: "Analgesic",
    label: "Ibuprofen Syrup — Dose & mL",
    keywords: ["ibuprofen", "brufen", "ibugesic", "advil", "calprofen", "syrup", "fever", "pain", "anti-inflammatory", "nsaid"],
    description: "10 mg/kg TDS (max 400 mg). Ibugesic-100: 20 mg/mL · Ibugesic-200 Forte: 40 mg/mL",
  },
  {
    id: "syrup-metronidazole",
    tab: "syrup",
    tabLabel: "Syrup Calculator",
    section: "Antibiotic",
    label: "Metronidazole Syrup — Amoeba / Giardia",
    keywords: ["metronidazole", "flagyl", "metrogyl", "aldezole", "syrup", "amoebiasis", "giardia", "anaerobic", "c difficile"],
    description: "7.5 mg/kg TDS (max 400 mg). Amoebiasis: 10 mg/kg TDS × 10 days. Flagyl-200 susp: 40 mg/mL",
  },
  {
    id: "syrup-ondansetron",
    tab: "syrup",
    tabLabel: "Syrup Calculator",
    section: "Antiemetic",
    label: "Ondansetron Syrup — Vomiting",
    keywords: ["ondansetron", "emeset", "ondem", "zofran", "vomikind", "syrup", "odt", "vomiting", "nausea", "antiemetic", "long qt"],
    description: "0.15 mg/kg TDS (max 4 mg if <15 kg, 8 mg if ≥15 kg). Emeset-2: 0.4 mg/mL. ODT available",
  },
  {
    id: "syrup-zinc",
    tab: "syrup",
    tabLabel: "Syrup Calculator",
    section: "ORS/Zinc",
    label: "Zinc — Diarrhoea Protocol",
    keywords: ["zinc", "diarrhoea", "ors", "oral rehydration", "iap who", "20 mg", "10 mg", "zincovit", "pedizinc", "zinc dispersible"],
    description: "<6 mo: 10 mg OD · ≥6 mo: 20 mg OD × 14 days. Mandatory WHO/IAP protocol with ORS",
  },
  {
    id: "syrup-prednisolone",
    tab: "syrup",
    tabLabel: "Syrup Calculator",
    section: "Steroid",
    label: "Prednisolone Syrup — Asthma / Nephrotic",
    keywords: ["prednisolone", "omnacortil", "wysolone", "prelone", "syrup", "asthma", "nephrotic syndrome", "steroid", "anti-inflammatory"],
    description: "Asthma: 1–2 mg/kg OD × 3–5 days. Nephrotic: 2 mg/kg OD × 6 weeks. Omnacortil-5 syrup: 1 mg/mL",
  },
  {
    id: "syrup-levetiracetam",
    tab: "syrup",
    tabLabel: "Syrup Calculator",
    section: "Anticonvulsant",
    label: "Levetiracetam Oral Solution",
    keywords: ["levetiracetam", "keppra", "levipil", "oral solution", "seizure", "epilepsy", "anticonvulsant", "100 mg/mL"],
    description: "10 mg/kg BD increasing to 30 mg/kg BD. Keppra 100 mg/mL oral solution",
  },

  // ─── SEDATION & ANALGESIA TAB ─────────────────────────────────────────────
  {
    id: "sed-psa-agents",
    tab: "sedation",
    tabLabel: "Sedation & Analgesia",
    section: "PSA Agents",
    label: "PSA Agent Comparison — Ketamine, Propofol, Midazolam",
    keywords: ["psa", "procedural sedation", "ketamine", "propofol", "midazolam", "fentanyl", "dexmedetomidine", "nitrous oxide", "ketofol", "etomidate", "dissociative", "sedation", "onset", "duration", "reversal"],
    description: "Weight-based IV/IN/IM doses: Ketamine 1–2 mg/kg IV, Propofol 1–2 mg/kg, Dexmedetomidine 0.5–1 mcg/kg",
  },
  {
    id: "sed-oral",
    tab: "sedation",
    tabLabel: "Sedation & Analgesia",
    section: "Oral Sedation",
    label: "Oral Sedatives — Midazolam, Triclofos, Dexmedetomidine IN",
    keywords: ["oral sedation", "midazolam oral", "triclofos", "pedicloryl", "chloral hydrate", "hydroxyzine", "atarax", "dexmedetomidine intranasal", "mri sedation", "procedural sedation oral", "pre-medication"],
    description: "Triclofos 75 mg/kg PO · Midazolam 0.5 mg/kg PO · Dexmedetomidine 2 mcg/kg IN (no respiratory depression)",
  },
  {
    id: "sed-local",
    tab: "sedation",
    tabLabel: "Sedation & Analgesia",
    section: "Local Anaesthetics",
    label: "Local Anaesthetic Safe Doses — Lignocaine, Bupivacaine",
    keywords: ["local anaesthetic", "lignocaine", "lidocaine", "bupivacaine", "ropivacaine", "max dose", "toxicity", "last", "intralipid"],
    description: "Lignocaine max 4.5 mg/kg plain (7 mg/kg with epi). Bupivacaine max 2 mg/kg. Never with adrenaline for digit blocks",
  },
  {
    id: "sed-nerve-blocks",
    tab: "sedation",
    tabLabel: "Sedation & Analgesia",
    section: "Nerve Blocks",
    label: "Paediatric Nerve Blocks — FANSB, Digital, IITB",
    keywords: ["nerve block", "fascia iliaca", "femoral", "digital block", "intercostal", "scalp block", "ilioinguinal", "wound infiltration", "ultrasound guided", "landmark technique", "regional anaesthesia"],
    description: "FANSB, digital blocks, fascia iliaca, intercostal. Aspirate q5 mL. Monitor for LAST",
  },
  {
    id: "sed-last",
    tab: "sedation",
    tabLabel: "Sedation & Analgesia",
    section: "LAST",
    label: "LAST — Local Anaesthetic Systemic Toxicity",
    keywords: ["last", "local anaesthetic toxicity", "systemic toxicity", "intralipid", "20% lipid emulsion", "cardiac arrest la", "seizure la", "tinnitus", "metallic taste", "bupivacaine toxicity"],
    description: "Intralipid 20%: 1.5 mL/kg bolus + 0.25–0.5 mL/kg/min infusion. Max 12 mL/kg. Reduce adrenaline dose",
  },

  // ─── NEONATAL TAB ─────────────────────────────────────────────────────────
  {
    id: "neo-nrp",
    tab: "neonatal",
    tabLabel: "Neonatal",
    section: "NRP",
    label: "Neonatal Resuscitation (NRP 2020)",
    keywords: ["nrp", "neonatal resuscitation", "ppv", "positive pressure ventilation", "t-piece", "bvm newborn", "spo2 targets", "hr check", "delayed cord clamping", "newborn", "delivery room"],
    description: "Delayed cord clamping ≥60 s · Initial FiO₂ 0.21 term · T-piece preferred · HR <60 → CPR 3:1",
  },
  {
    id: "neo-apgar",
    tab: "neonatal",
    tabLabel: "Neonatal",
    section: "APGAR",
    label: "APGAR Score",
    keywords: ["apgar", "score", "newborn assessment", "tone", "grimace", "colour", "heart rate", "respiration", "1 minute", "5 minutes", "neonatal"],
    description: "APGAR at 1 & 5 min. Score ≥7 normal · 4–6 moderate · <4 severe. APGAR does NOT guide resuscitation",
  },
  {
    id: "neo-drugs",
    tab: "neonatal",
    tabLabel: "Neonatal",
    section: "Doses",
    label: "Neonatal Drug Doses — ETT Depth, UVC, Adrenaline",
    keywords: ["neonatal dose", "ett depth neonate", "uvc", "umbilical venous catheter", "adrenaline neonate", "phenobarbital neonate", "caffeine neonate", "vitamin k birth", "d10w neonatal"],
    description: "Adrenaline IV 0.01–0.03 mg/kg · ETT depth (6 + weight) cm · UVC (1.5 × weight + 5.5) cm",
  },
  {
    id: "neo-vitals",
    tab: "neonatal",
    tabLabel: "Neonatal",
    section: "Vitals",
    label: "Neonatal Normal Vitals & SpO₂ Targets",
    keywords: ["neonatal vitals", "normal neonate", "neonatal heart rate", "neonatal rr", "neonatal bp", "temperature neonate", "spo2 targets nrp", "preductal", "postductal"],
    description: "HR 100–160, RR 40–60, SpO₂ targets: 1 min 60–65% → 10 min 85–95%",
  },
  {
    id: "neo-stops",
    tab: "neonatal",
    tabLabel: "Neonatal",
    section: "STOPS",
    label: "STOPS — Neonatal Mortality Score",
    keywords: ["stops", "neonatal mortality", "prognosis", "sensorium", "temperature", "oxygenation", "perfusion", "sugar", "nicu score", "bedside"],
    description: "STOPS score (0–10): Sensorium + Temperature + Oxygenation + Perfusion + Sugar. >2 predicts mortality ~83%",
  },

  // ─── TRAUMA TAB ───────────────────────────────────────────────────────────
  {
    id: "trauma-primary",
    tab: "trauma",
    tabLabel: "Trauma Resuscitation",
    section: "Primary Survey",
    label: "xABCDE Primary Survey — ATLS 11th Ed 2025",
    keywords: ["primary survey", "xabcde", "atls", "haemorrhage control", "tourniquet", "airway trauma", "c-spine", "mils", "breathing trauma", "tension pneumothorax", "fast", "damage control"],
    description: "x = Exsanguinating haemorrhage first. ABC: airway MILS, breathing PTX, circulation blood products, disability GCS, exposure",
  },
  {
    id: "trauma-shock",
    tab: "trauma",
    tabLabel: "Trauma Resuscitation",
    section: "Shock & Fluids",
    label: "Haemorrhagic Shock Classification",
    keywords: ["haemorrhagic shock", "class I II III IV", "blood loss", "ebv", "tachycardia", "hypotension", "permissive hypotension", "blood products", "damage control resuscitation", "dcr", "mtp"],
    description: "EBV by weight, Class I–IV based on % loss. Blood products 1:1:1 ratio. Permissive hypotension until surgical control",
  },
  {
    id: "trauma-txa",
    tab: "trauma",
    tabLabel: "Trauma Resuscitation",
    section: "Shock & Fluids",
    label: "Tranexamic Acid (TXA) — Within 3 Hours",
    keywords: ["txa", "tranexamic acid", "15 mg/kg", "major haemorrhage", "trauma bleeding", "crash-2", "within 3 hours", "antifibrinolytic"],
    description: "TXA 15 mg/kg (max 1 g) IV over 10 min, then 2 mg/kg/hr × 8 hr. Must give within 3 hours of injury",
  },
  {
    id: "trauma-tbi",
    tab: "trauma",
    tabLabel: "Trauma Resuscitation",
    section: "TBI",
    label: "TBI — GCS, PECARN CT Rule, ICP Management",
    keywords: ["tbi", "traumatic brain injury", "gcs", "glasgow coma scale", "pecarn", "ct head", "intracranial pressure", "icp", "mannitol", "hypertonic saline", "herniation", "cushing triad"],
    description: "GCS ≤8 = severe TBI. PECARN CT decision rule. Osmotherapy: 3% NaCl 2–5 mL/kg or Mannitol 0.5 g/kg",
  },
  {
    id: "trauma-pecarn",
    tab: "trauma",
    tabLabel: "Trauma Resuscitation",
    section: "TBI",
    label: "PECARN CT Rule — Head Injury",
    keywords: ["pecarn", "head injury", "ct head", "citbi", "clinically important tbi", "gcs 14 15", "scalp haematoma", "loss of consciousness", "altered mental status", "basilar skull", "raccoon eyes", "battle sign"],
    description: "<2 yr: GCS ≤14, AMS, palpable skull #, non-frontal haematoma, LOC ≥5 s, severe mechanism. ≥2 yr: GCS ≤14, AMS, basilar #",
  },

  // ─── MANAGEMENT ALGORITHMS TAB ───────────────────────────────────────────
  {
    id: "algo-ed",
    tab: "algorithms",
    tabLabel: "Management Algorithms",
    section: "ED Management",
    label: "ED Management Algorithms — Sepsis, DKA, Meningitis, Asthma",
    keywords: ["septic shock protocol", "dka protocol", "status epilepticus protocol", "meningitis protocol", "anaphylaxis protocol", "acute asthma", "croup algorithm", "dengue management", "neonatal resus algorithm"],
    description: "Diagnostic + management phases for 9 critical/common conditions. Phase-based with drug doses",
  },
  {
    id: "algo-aha",
    tab: "algorithms",
    tabLabel: "Management Algorithms",
    section: "AHA Algorithms",
    label: "AHA PALS 2025 Algorithms",
    keywords: ["pals", "aha", "2025", "advanced cardiac life support", "pulseless arrest", "bradycardia algorithm", "tachycardia algorithm", "cpr 2025", "compression ventilation ratio", "rosc"],
    description: "Updated 2025 AHA PALS algorithms: CPR cadence, defibrillation, post-arrest care. Key 2025 changes",
  },
  {
    id: "algo-guidelines",
    tab: "algorithms",
    tabLabel: "Management Algorithms",
    section: "Clinical Guidelines",
    label: "IAP Clinical Guidelines 2019–2023",
    keywords: ["iap guidelines", "indian academy pediatrics", "asthma iap", "bronchiolitis iap", "croup iap", "seizure iap", "sepsis iap", "dka iap", "dengue iap", "meningitis iap", "neonatal iap", "community pneumonia"],
    description: "IAP 2019–2023 key points for asthma, bronchiolitis, croup, SE, sepsis, DKA, dengue, meningitis, pneumonia",
  },
  {
    id: "algo-pathways",
    tab: "algorithms",
    tabLabel: "Management Algorithms",
    section: "Interactive Pathways",
    label: "Interactive Decision-Tree Pathways",
    keywords: ["pathway", "decision tree", "interactive", "asthma severity", "dehydration pathway", "febrile seizure", "bronchiolitis pathway", "croup severity", "care plan", "pdf export"],
    description: "Click-through clinical pathways with weight-based drug doses at endpoint. Export care plan PDF",
  },
  {
    id: "algo-differentials",
    tab: "algorithms",
    tabLabel: "Management Algorithms",
    section: "Differentials",
    label: "Differential Diagnosis — Wheeze, Stridor, Altered Consciousness",
    keywords: ["differential diagnosis", "ddx", "wheeze differentials", "stridor differentials", "altered consciousness", "rash differentials", "abdominal pain", "limp", "mnemonics", "red flags"],
    description: "Diagnosis tables by chief complaint with age, clues, workup. Red flags. Mnemonics (e.g. MUDPILES)",
  },

  // ─── PREHOSPITAL TAB ──────────────────────────────────────────────────────
  {
    id: "preh-triage",
    tab: "prehospital",
    tabLabel: "Prehospital",
    section: "Triage",
    label: "Prehospital Triage — AVPU & ABCDE",
    keywords: ["triage", "avpu", "alert", "voice", "pain", "unresponsive", "abcde prehospital", "airway prehospital", "breathing prehospital", "circulation prehospital", "prem", "rapid assessment"],
    description: "AVPU consciousness scale. PREM triangle: ABCDE rapid assessment with simultaneous intervention",
  },
  {
    id: "preh-bls",
    tab: "prehospital",
    tabLabel: "Prehospital",
    section: "BLS & CPR",
    label: "Basic Life Support & CPR — Prehospital",
    keywords: ["bls", "basic life support", "cpr prehospital", "rescue breathing", "chest compressions", "adrenaline arrest", "15:2 prehospital"],
    description: "Check responsiveness, 2 rescue breaths, 15:2 CPR. Adrenaline: 0.01 mg/kg IV/IO q3–5 min",
  },
  {
    id: "preh-choking",
    tab: "prehospital",
    tabLabel: "Prehospital",
    section: "Choking",
    label: "Choking — Heimlich / Back Blows",
    keywords: ["choking", "heimlich", "back blows", "chest thrusts", "foreign body airway", "infant choking", "child choking", "obstruction", "blind finger sweep"],
    description: "Child ≥1 yr: 5 abdominal thrusts. Infant <1 yr: 5 back blows + 5 chest thrusts. NO blind finger sweep",
  },
  {
    id: "preh-seizure",
    tab: "prehospital",
    tabLabel: "Prehospital",
    section: "Seizures",
    label: "Seizure First Aid — Midazolam IN/IM",
    keywords: ["seizure prehospital", "convulsion", "midazolam prehospital", "in midazolam", "status prehospital", "recovery position", "anticonvulsant prehospital", "febrile seizure"],
    description: "Recovery position, O₂, midazolam 0.2 mg/kg IM/IN/buccal. Rule out posturing from hypoxia/shock first",
  },
  {
    id: "preh-poison",
    tab: "prehospital",
    tabLabel: "Prehospital",
    section: "Poisoning",
    label: "Poisoning — Activated Charcoal & Antidotes",
    keywords: ["poisoning", "activated charcoal", "naloxone", "atropine organophosphate", "flumazenil", "co poisoning", "corrosive ingestion", "do not induce vomiting"],
    description: "Activated charcoal within 2 hr. Never induce vomiting. CO → O₂. OP → atropine. Key antidotes by poison",
  },
  {
    id: "preh-poison-centres",
    tab: "prehospital",
    tabLabel: "Prehospital",
    section: "Poison Centres",
    label: "Poison Information Centres — India (24 hr)",
    keywords: ["poison centre", "poison control", "aiims delhi poison", "amrita kochi poison", "cmc vellore poison", "egmore poison", "nimhans", "kem mumbai", "1800-425-1213", "antidote guidance"],
    description: "AIIMS: 011-26850691 · Amrita Kochi: 484-2858056 · CMC Vellore: 1800-425-1213 (toll-free) · Egmore: 044-281-92922",
  },
  {
    id: "preh-envenomation",
    tab: "prehospital",
    tabLabel: "Prehospital",
    section: "Envenomation",
    label: "Snake Bite — RIGHT Mnemonic / Scorpion — Prazosin",
    keywords: ["snake bite", "right mnemonic", "asv", "antivenom", "tourniquet snake", "scorpion", "prazosin", "autonomic storm", "envenomation"],
    description: "Snake: Reassure · Immobilise · Get to hospital · Tell doctor. Scorpion: prazosin 30 mcg/kg for autonomic storm",
  },
  {
    id: "preh-burns-ph",
    tab: "prehospital",
    tabLabel: "Prehospital",
    section: "Burns",
    label: "Burns First Aid — Cool Running Water 20 min",
    keywords: ["burns first aid", "cool water", "tbsa estimation", "lund browder prehospital", "inhalation injury", "facial burns", "stridor burns"],
    description: "Cool running water 20 min within 30 min of burn. No ice. Cover. Inhalation injury → early intubation",
  },

  // ─── IMMUNISATION TAB ─────────────────────────────────────────────────────
  {
    id: "imm-iap",
    tab: "immunisation",
    tabLabel: "Immunisation",
    section: "IAP Schedule",
    label: "IAP-ACVIP 2023 Immunisation Schedule",
    keywords: ["iap schedule", "immunisation", "vaccine", "acvip 2023", "dtap", "dtwp", "ipv", "pcv", "rotavirus", "mmr", "varicella", "hpv", "typhoid tcv", "hepatitis a", "influenza", "meningococcal"],
    description: "Complete IAP-ACVIP 2023 schedule from birth to 18 yr. New: HPV for boys, Td at 16–18 yr",
  },
  {
    id: "imm-uip",
    tab: "immunisation",
    tabLabel: "Immunisation",
    section: "NIP/UIP Schedule",
    label: "National Immunisation Programme (NIP/UIP) — GoI",
    keywords: ["uip", "nip", "government schedule", "bcg", "opv", "hbv", "pentavalent", "fipv", "mr", "je", "vitamin a", "td", "free vaccine"],
    description: "GoI/NHM free vaccination schedule: BCG, OPV, Pentavalent, fIPV, Rotavirus (select states), PCV, MR, JE, Td",
  },
  {
    id: "imm-special",
    tab: "immunisation",
    tabLabel: "Immunisation",
    section: "Special Vaccines",
    label: "Special Vaccines — Rabies PEP, Cholera, JE, Meningococcal",
    keywords: ["rabies pep", "post exposure prophylaxis", "rig", "rabies immunoglobulin", "cholera ocv", "shanchol", "je vaccine", "sa14", "meningococcal", "menacwy", "menb", "bexsero", "hajj", "asplenia"],
    description: "Rabies PEP: 5-dose Essen or 4-visit Thai Red Cross ID. RIG 20 IU/kg wound infiltration Day 0",
  },
  {
    id: "imm-catchup",
    tab: "immunisation",
    tabLabel: "Immunisation",
    section: "Catch-up",
    label: "Catch-Up Vaccination Principles",
    keywords: ["catch up vaccine", "missed vaccine", "delayed vaccine", "never restart", "minimum interval", "same visit", "partial immunisation", "incomplete schedule"],
    description: "Never restart a series. Give all due vaccines same visit. Respect minimum age/intervals",
  },
  {
    id: "imm-nnf",
    tab: "immunisation",
    tabLabel: "Immunisation",
    section: "National Guidelines",
    label: "NNF Guidelines — Neonatal Sepsis, ROP, Jaundice",
    keywords: ["nnf", "neonatal sepsis", "eos", "los", "early onset sepsis", "late onset sepsis", "rop screening", "retinopathy prematurity", "hyperbilirubinaemia", "phototherapy", "exchange transfusion", "g6pd"],
    description: "EOS: Ampicillin + Gentamicin. LOS: Pip-Tazo or Clox + Amikacin. ROP screen ≤1750 g or ≤34 wk",
  },
  {
    id: "imm-nvbdcp",
    tab: "immunisation",
    tabLabel: "Immunisation",
    section: "National Guidelines",
    label: "NVBDCP — Malaria & Dengue Guidelines",
    keywords: ["malaria", "nvbdcp", "plasmodium vivax", "plasmodium falciparum", "artemether lumefantrine", "chloroquine", "artesunate iv", "primaquine", "g6pd malaria", "dengue", "ns1", "igm dengue", "group b dengue", "dengue platelet"],
    description: "P. vivax: Chloroquine + Primaquine 14d. P. falciparum: AL/Coartem. Severe: IV Artesunate 2.4 mg/kg",
  },
  {
    id: "imm-ntep",
    tab: "immunisation",
    tabLabel: "Immunisation",
    section: "National Guidelines",
    label: "NTEP — Paediatric TB Guidelines 2022",
    keywords: ["tb", "tuberculosis", "ntep", "rntcp", "isoniazid", "rifampicin", "pyrazinamide", "ethambutol", "fdc", "akurit", "nikshay", "mantoux", "ltbi", "mdr tb", "bedaquiline"],
    description: "2HRZE/4HR with weight-based FDC. LTBI: INH 10 mg/kg × 6 months. NIKSHAY mandatory reporting",
  },
  {
    id: "imm-sam",
    tab: "immunisation",
    tabLabel: "Immunisation",
    section: "National Guidelines",
    label: "SAM — Severe Acute Malnutrition Management",
    keywords: ["sam", "severe acute malnutrition", "muac", "weight for height", "rutf", "plumpy nut", "f-75", "f-100", "hypoglycaemia sam", "hypothermia sam", "fluid sam", "avoid bolus sam", "cmam", "deic"],
    description: "SAM: MUAC <11.5 cm or WHZ <-3. Avoid routine IV bolus. F-75→F-100. Glucose q2–3h. Amoxicillin prophylaxis",
  },

  // ─── CO-PILOT TAB ─────────────────────────────────────────────────────────
  {
    id: "copilot-main",
    tab: "copilot",
    tabLabel: "Co-Pilot",
    section: "AI Assistant",
    label: "Co-Pilot — AI Clinical Assistant",
    keywords: ["copilot", "ai", "assistant", "clinical support", "ask", "chat"],
    description: "AI-powered clinical assistant for paediatric emergency queries",
  },
];
