// ═══════════════════════════════════════════════════════════════════════════
// PedResus Search Index — Complete Rewrite
// One entry per specific item per tab. drugId/itemId enables auto-expand.
// ═══════════════════════════════════════════════════════════════════════════

export const SEARCH_INDEX = [

  // ─── CALCULATOR ────────────────────────────────────────────────────────────
  {
    id: "calc-weight", tab: "calculator", tabLabel: "Calculator",
    section: "Weight", label: "Weight Calculator",
    keywords: ["weight", "kg", "estimate", "broselow", "length", "age"],
    description: "Calculate or estimate patient weight by age, length, or Broselow tape",
  },

  // ─── EQUIPMENT ─────────────────────────────────────────────────────────────
  {
    id: "eq-ett", tab: "equipment", tabLabel: "Equipments",
    section: "Reference Table", label: "ETT Size & Depth",
    keywords: ["ett", "endotracheal tube", "intubation", "uncuffed", "cuffed", "oral", "nasal", "age formula", "size"],
    description: "ETT uncuffed: (age÷4)+4 · Cuffed: (age÷4)+3.5 · Depth: (age÷2)+12 cm oral",
  },
  {
    id: "eq-suction", tab: "equipment", tabLabel: "Equipments",
    section: "Reference Table", label: "Suction Catheter Size",
    keywords: ["suction", "french", "catheter", "airway suction"],
    description: "Suction catheter French size by weight and age",
  },
  {
    id: "eq-lma", tab: "equipment", tabLabel: "Equipments",
    section: "Reference Table", label: "LMA Size",
    keywords: ["lma", "laryngeal mask", "supraglottic", "airway"],
    description: "LMA size by weight — 1 (<5kg), 1.5 (5–10kg), 2 (10–20kg), 2.5 (20–30kg)",
  },
  {
    id: "eq-defib", tab: "equipment", tabLabel: "Equipments",
    section: "Reference Table", label: "Defibrillation & Cardioversion",
    keywords: ["defibrillation", "cardioversion", "joules", "shock", "vf", "vt", "aed", "4 j/kg"],
    description: "Defibrillation 4 J/kg (max 10 J/kg) · Cardioversion 0.5–1 J/kg",
  },
  {
    id: "eq-ngt", tab: "equipment", tabLabel: "Equipments",
    section: "Reference Table", label: "NGT Size",
    keywords: ["ngt", "nasogastric", "tube", "feeding tube", "french"],
    description: "NGT French size by weight/age",
  },
  {
    id: "eq-iv-gauge", tab: "equipment", tabLabel: "Equipments",
    section: "Reference Table", label: "IV Access — Cannula Gauge",
    keywords: ["iv", "cannula", "gauge", "access", "venflon", "intravenous"],
    description: "IV cannula gauge by age — neonate 24G, infant 22–24G, child 20–22G",
  },
  {
    id: "eq-difficult-airway", tab: "equipment", tabLabel: "Equipments",
    section: "Difficult Airway", label: "Difficult Airway Prediction (LEMON / MOANS / RODS)",
    keywords: ["difficult airway", "lemon", "moans", "rods", "mallampati", "micrognathia", "pierre robin", "treacher collins", "predict"],
    description: "AIDAA 2022 — structural and acquired difficult airway predictors",
  },
  {
    id: "eq-vortex", tab: "equipment", tabLabel: "Equipments",
    section: "Difficult Airway", label: "Vortex Approach — CICO / Neck Rescue",
    keywords: ["vortex", "cico", "cannot intubate", "cannot oxygenate", "neck rescue", "efona", "cricothyrotomy", "surgical airway"],
    description: "3 lifelines: Face Mask → SGA → ETT → Neck Rescue (eFONA)",
  },
  {
    id: "eq-fob", tab: "equipment", tabLabel: "Equipments",
    section: "Difficult Airway", label: "Fibreoptic Bronchoscope Sizing",
    keywords: ["fibreoptic", "fob", "bronchoscope", "awake intubation", "scope size"],
    description: "Scope OD by weight: <3 kg 2.2 mm → adolescent 4.9 mm",
  },
  {
    id: "eq-bvm", tab: "equipment", tabLabel: "Equipments",
    section: "Monitoring", label: "BVM Technique",
    keywords: ["bvm", "bag mask", "bag valve", "ec clamp", "jaw thrust", "two person", "opa", "npa"],
    description: "EC technique, 2-person preferred, OPA/NPA sizing, tidal volume 6–8 mL/kg",
  },
  {
    id: "eq-spo2", tab: "equipment", tabLabel: "Equipments",
    section: "Monitoring", label: "Pulse Oximetry — Limitations & SpO₂ Targets",
    keywords: ["spo2", "pulse oximetry", "saturation", "co poisoning", "methhaemoglobin", "preductal", "postductal", "pphn"],
    description: "SpO₂ targets, probe sites, COHb false normal, MetHb reads ~85%",
  },
  {
    id: "eq-bp", tab: "equipment", tabLabel: "Equipments",
    section: "Monitoring", label: "Blood Pressure Cuff Selection",
    keywords: ["blood pressure", "bp cuff", "nibp", "cuff size", "falsely high", "falsely low"],
    description: "Cuff width = 40% arm circumference. Too small → falsely HIGH",
  },

  // ─── VITALS ────────────────────────────────────────────────────────────────
  {
    id: "vitals-calculator", tab: "vitals", tabLabel: "Vitals",
    section: "Live Calculator", label: "Live Vitals Calculator — Normal vs Abnormal",
    keywords: ["vitals", "live calculator", "normal", "abnormal", "tachycardia", "bradycardia", "tachypnoea", "hypotension", "fever", "spo2"],
    description: "Enter HR, RR, BP, SpO₂, temp — auto-flags abnormal values by age band",
  },
  {
    id: "vitals-reference", tab: "vitals", tabLabel: "Vitals",
    section: "Quick Reference", label: "Normal Vital Signs by Age",
    keywords: ["normal vitals", "heart rate", "hr", "respiratory rate", "rr", "blood pressure", "sbp", "neonate", "infant", "toddler", "adolescent", "pals"],
    description: "Age-specific normal HR, RR, SBP ranges — PALS 2020",
  },
  {
    id: "vitals-ecg-vf", tab: "vitals", tabLabel: "Vitals",
    section: "ECG & Rhythms", label: "VF — Ventricular Fibrillation",
    keywords: ["vf", "ventricular fibrillation", "shockable", "defibrillation", "arrest", "chaotic"],
    description: "Chaotic irregular deflections — defibrillate 4 J/kg immediately",
  },
  {
    id: "vitals-ecg-vt", tab: "vitals", tabLabel: "Vitals",
    section: "ECG & Rhythms", label: "Pulseless VT",
    keywords: ["vt", "ventricular tachycardia", "pulseless vt", "pvt", "wide qrs", "shockable", "torsades"],
    description: "Wide bizarre QRS, no pulse — treat as VF. Torsades: MgSO₄",
  },
  {
    id: "vitals-ecg-asystole", tab: "vitals", tabLabel: "Vitals",
    section: "ECG & Rhythms", label: "Asystole",
    keywords: ["asystole", "flat line", "no activity", "cardiac arrest", "non shockable"],
    description: "Flat line — CPR + adrenaline 0.01 mg/kg. Do NOT defibrillate",
  },
  {
    id: "vitals-ecg-pea", tab: "vitals", tabLabel: "Vitals",
    section: "ECG & Rhythms", label: "PEA — Pulseless Electrical Activity",
    keywords: ["pea", "pulseless electrical activity", "organised", "no pulse", "4h4t", "reversible causes"],
    description: "Organised ECG — no palpable pulse. Find reversible cause (4H4T)",
  },
  {
    id: "vitals-ecg-svt", tab: "vitals", tabLabel: "Vitals",
    section: "ECG & Rhythms", label: "SVT — Supraventricular Tachycardia",
    keywords: ["svt", "supraventricular tachycardia", "adenosine", "narrow qrs", "vagal", "cardioversion", ">220 bpm"],
    description: "Infants >220 bpm — vagal → adenosine 0.1 mg/kg → cardioversion",
  },
  {
    id: "vitals-ecg-brady", tab: "vitals", tabLabel: "Vitals",
    section: "ECG & Rhythms", label: "Symptomatic Bradycardia",
    keywords: ["bradycardia", "slow heart rate", "atropine", "hr <60", "poor perfusion", "cpr"],
    description: "HR <60 + poor perfusion → O₂ first → atropine → CPR if no response",
  },
  {
    id: "vitals-ecg-wpw", tab: "vitals", tabLabel: "Vitals",
    section: "ECG & Rhythms", label: "WPW — Wolff-Parkinson-White",
    keywords: ["wpw", "wolff parkinson white", "pre excitation", "delta wave", "short pr", "ablation"],
    description: "Short PR + delta wave + wide QRS. Pre-excited AF → DC cardioversion",
  },
  {
    id: "vitals-ecg-chb", tab: "vitals", tabLabel: "Vitals",
    section: "ECG & Rhythms", label: "Complete Heart Block (3°)",
    keywords: ["complete heart block", "third degree", "chb", "av block", "pacing", "independent p waves"],
    description: "P waves and QRS completely independent — pacing required",
  },
  {
    id: "vitals-trending", tab: "vitals", tabLabel: "Vitals",
    section: "Vitals Trending", label: "Vitals Trending — Serial Monitoring",
    keywords: ["trending", "serial vitals", "chart", "csv", "record", "monitor", "trend"],
    description: "Record serial vitals, chart trends, export CSV with patient details",
  },

  // ─── RESUSCITATION ─────────────────────────────────────────────────────────
  {
    id: "resus-rsi", tab: "resuscitation", tabLabel: "Resuscitation",
    section: "RSI Quickstart", label: "RSI — Rapid Sequence Intubation",
    keywords: ["rsi", "rapid sequence intubation", "intubation", "ketamine", "rocuronium", "suxamethonium", "propofol", "7 ps"],
    description: "Weight-based RSI: induction + paralysis + pre-medication doses",
  },
  {
    id: "resus-infusions", tab: "resuscitation", tabLabel: "Resuscitation",
    section: "Infusions (mL/hr)", label: "Vasoactive Infusion Calculator",
    keywords: ["infusion", "dopamine", "noradrenaline", "adrenaline", "milrinone", "mL/hr", "mcg/kg/min", "vasopressor", "inotrope"],
    description: "mL/hr calculator for vasoactive infusions based on concentration and weight",
  },
  {
    id: "resus-rule6", tab: "resuscitation", tabLabel: "Resuscitation",
    section: "Rule of 6s", label: "Rule of 6s — Infusion Mixing",
    keywords: ["rule of 6", "rule of 6s", "infusion mixing", "concentration", "mcg/kg/min", "neonatal infusion"],
    description: "Rule of 6s for mixing weight-based infusions in neonates and small children",
  },
  {
    id: "resus-7ps", tab: "resuscitation", tabLabel: "Resuscitation",
    section: "7 Ps Checklist", label: "7 Ps RSI Checklist",
    keywords: ["7 ps", "rsi checklist", "preparation", "preoxygenation", "pretreatment", "paralysis", "positioning", "post intubation"],
    description: "Preparation · Preoxygenation · Pretreatment · Push the drugs · Paralysis · Position · Post-intubation",
  },
  {
    id: "resus-icd", tab: "resuscitation", tabLabel: "Resuscitation",
    section: "ICD Insertion", label: "ICD / Chest Tube Insertion",
    keywords: ["icd", "chest tube", "intercostal drain", "pneumothorax", "haemothorax", "blunt dissection", "french size"],
    description: "Indications, tube size by weight, technique, post-procedure care",
  },

  // ─── VENTILATOR ────────────────────────────────────────────────────────────
  {
    id: "vent-settings", tab: "ventilator", tabLabel: "Ventilator",
    section: "Settings", label: "Ventilator Settings — Weight-Based",
    keywords: ["ventilator", "tidal volume", "peep", "rate", "fio2", "pip", "ie ratio", "prvc", "simv", "pc ac", "vc ac"],
    description: "Vt 6–8 mL/kg, PEEP 5–8, FiO₂ titrate. Mode recommendations by condition",
  },
  {
    id: "vent-ards", tab: "ventilator", tabLabel: "Ventilator",
    section: "Settings", label: "ARDS — Lung Protective Strategy",
    keywords: ["ards", "lung protective", "low tidal volume", "permissive hypercapnia", "plateau pressure", "driving pressure", "peep ladder", "prone"],
    description: "Vt 4–6 mL/kg IBW · Plateau ≤30 · Driving pressure ≤15 · ARDSnet",
  },
  {
    id: "vent-troubleshoot", tab: "ventilator", tabLabel: "Ventilator",
    section: "Troubleshoot", label: "High PIP / Low Vt — DOPE Mnemonic",
    keywords: ["high pip", "high pressure", "dope", "displaced", "obstructed", "pneumothorax", "equipment failure", "auto peep", "alarm"],
    description: "DOPE: Displaced · Obstructed · Pneumothorax · Equipment failure",
  },
  {
    id: "vent-waveforms", tab: "ventilator", tabLabel: "Ventilator",
    section: "Waveforms", label: "Ventilator Waveforms",
    keywords: ["waveforms", "pressure scalar", "flow scalar", "inspiratory hold", "plateau pressure", "expiratory hold", "shark fin", "flow starvation"],
    description: "Live waveform simulator + library. Inspiratory/expiratory hold manoeuvres",
  },
  {
    id: "etco2", tab: "equipment", tabLabel: "Equipment",
    section: "Monitoring", label: "EtCO₂ / Capnography",
    keywords: ["etco2", "capnography", "end tidal co2", "rosc", "oesophageal intubation", "shark fin co2", "cpr monitoring"],
    description: "Normal capnogram phases, shark-fin pattern, oesophageal intubation, ROSC",
  },
  {
    id: "vent-weaning", tab: "ventilator", tabLabel: "Ventilator",
    section: "Weaning", label: "Weaning & Spontaneous Breathing Trial (SBT)",
    keywords: ["weaning", "extubation", "sbt", "spontaneous breathing trial", "cuff leak", "post extubation stridor", "hfnc", "niv"],
    description: "SBT: PS 5–8 + PEEP 5 for 30–120 min. Pre-extubation dexamethasone",
  },

  // ─── FLUIDS ────────────────────────────────────────────────────────────────
  {
    id: "fluids-maintenance", tab: "fluids", tabLabel: "Fluids",
    section: "Maintenance", label: "Maintenance Fluid — 4-2-1 Rule",
    keywords: ["maintenance", "4-2-1", "holliday segar", "daily fluid", "mL/hr", "fluid rate"],
    description: "4 mL/kg/hr for first 10 kg + 2 for next 10 + 1 for remainder",
  },
  {
    id: "fluids-bolus", tab: "fluids", tabLabel: "Fluids",
    section: "Maintenance", label: "Fluid Bolus — Resuscitation",
    keywords: ["bolus", "resuscitation", "20 mL/kg", "normal saline", "shock bolus", "fluid challenge"],
    description: "20 mL/kg isotonic crystalloid over 5–20 min. Up to 60 mL/kg first hour",
  },
  {
    id: "fluids-dka", tab: "fluids", tabLabel: "Fluids",
    section: "DKA", label: "DKA Fluid Protocol",
    keywords: ["dka", "diabetic ketoacidosis", "48 hours", "deficit", "cerebral oedema", "insulin infusion", "ispad"],
    description: "Deficit over 48 hr. Insulin 0.05–0.1 units/kg/hr after 1 hr fluids",
  },
  {
    id: "fluids-dehydration", tab: "fluids", tabLabel: "Fluids",
    section: "Diarrhoea", label: "Dehydration — ORT Plan A/B/C",
    keywords: ["dehydration", "ort", "oral rehydration", "ors", "plan a", "plan b", "plan c", "who imci", "diarrhoea"],
    description: "WHO/IAP: Plan B (ORS 100 mL/kg/4hr), Plan C (IV NS 20 mL/kg). Zinc mandatory",
  },
  {
    id: "fluids-burns", tab: "fluids", tabLabel: "Fluids",
    section: "Burns", label: "Parkland Formula — Burns Fluid",
    keywords: ["parkland", "burns", "tbsa", "lund browder", "lactated ringer", "burn fluid"],
    description: "3 mL/kg/%TBSA LR over 24 hr. Half in first 8 hr. UO target 1 mL/kg/hr",
  },
  {
    id: "fluids-shock", tab: "fluids", tabLabel: "Fluids",
    section: "Shock", label: "Shock Types & Management",
    keywords: ["shock", "hypovolaemic", "distributive", "cardiogenic", "obstructive", "septic", "vasopressor", "dobutamine"],
    description: "Fluid strategy and vasoactive drugs for all shock types",
  },
  {
    id: "fluids-periop", tab: "fluids", tabLabel: "Fluids",
    section: "Peri-op", label: "EBV / Allowable Blood Loss / NPO Deficit",
    keywords: ["ebv", "estimated blood volume", "allowable blood loss", "npo deficit", "transfusion", "pRBC", "perioperative"],
    description: "EBV by age-band, ABL formula, NPO deficit, pRBC trigger Hb <7",
  },

  // ─── ABG ───────────────────────────────────────────────────────────────────
  {
    id: "abg-interpreter", tab: "abg", tabLabel: "ABG",
    section: "Interpreter", label: "ABG Step-by-Step Interpretation",
    keywords: ["abg", "arterial blood gas", "ph", "paco2", "hco3", "bicarbonate", "acidosis", "alkalosis", "metabolic", "respiratory", "winters formula"],
    description: "pH → Primary disorder → Compensation → Anion gap → Delta-delta",
  },
  {
    id: "abg-anion-gap", tab: "abg", tabLabel: "ABG",
    section: "Anion Gap", label: "Anion Gap & MUDPILES",
    keywords: ["anion gap", "hagma", "nagma", "mudpiles", "methanol", "uraemia", "dka", "lactic acidosis", "salicylates"],
    description: "AG = Na − (Cl + HCO₃) · Normal 8–12. MUDPILES differential",
  },
  {
    id: "abg-oxygenation", tab: "abg", tabLabel: "ABG",
    section: "Oxygenation", label: "A-a Gradient & Oxygenation",
    keywords: ["a-a gradient", "alveolar arterial", "fio2", "pao2", "vq mismatch", "shunt", "hypoxaemia"],
    description: "A-a gradient = (FiO₂ × 713 − PaCO₂/0.8) − PaO₂. Normal <15 mmHg",
  },

  // ─── DRUGS — IV (one per drug) ─────────────────────────────────────────────
  {
    id: "drug-adrenaline-arrest", tab: "drugs", tabLabel: "Drugs",
    section: "Drug Doses", drugId: "adrenaline-arrest",
    label: "Adrenaline — Cardiac Arrest",
    keywords: ["adrenaline", "epinephrine", "cardiac arrest", "0.01 mg/kg", "1:10000", "iv", "io"],
    description: "0.01 mg/kg IV/IO (0.1 mL/kg of 1:10,000). Repeat every 3–5 min",
  },
  {
    id: "drug-adrenaline-im", tab: "drugs", tabLabel: "Drugs",
    section: "Drug Doses", drugId: "adrenaline-im",
    label: "Adrenaline IM — Anaphylaxis",
    keywords: ["adrenaline", "epinephrine", "anaphylaxis", "im", "1:1000", "anterolateral thigh", "epipen", "0.01 mg/kg"],
    description: "0.01 mg/kg IM (max 0.5 mg) anterolateral thigh. Repeat q5–15 min",
  },
  {
    id: "drug-atropine", tab: "drugs", tabLabel: "Drugs",
    section: "Drug Doses", drugId: "atropine",
    label: "Atropine — Bradycardia / Pre-intubation",
    keywords: ["atropine", "bradycardia", "pre intubation", "0.02 mg/kg", "slow heart rate"],
    description: "0.02 mg/kg IV (min 0.1 mg, max 0.5 mg). HR <60 + poor perfusion → CPR",
  },
  {
    id: "drug-adenosine", tab: "drugs", tabLabel: "Drugs",
    section: "Drug Doses", drugId: "adenosine",
    label: "Adenosine — SVT",
    keywords: ["adenosine", "svt", "supraventricular tachycardia", "rapid push", "0.1 mg/kg"],
    description: "0.1 mg/kg rapid IV push (max 6 mg). 2nd dose 0.2 mg/kg (max 12 mg)",
  },
  {
    id: "drug-amiodarone", tab: "drugs", tabLabel: "Drugs",
    section: "Drug Doses", drugId: "amiodarone",
    label: "Amiodarone — VF/VT / SVT",
    keywords: ["amiodarone", "vf", "vt", "svt", "refractory", "5 mg/kg"],
    description: "5 mg/kg IV/IO bolus (max 300 mg) for refractory VF/pulseless VT",
  },
  {
    id: "drug-naloxone", tab: "drugs", tabLabel: "Drugs",
    section: "Drug Doses", drugId: "naloxone",
    label: "Naloxone — Opioid Overdose",
    keywords: ["naloxone", "narcan", "opioid", "overdose", "reversal", "respiratory depression"],
    description: "0.1 mg/kg IV/IM/IN (max 2 mg). Titrate to respiratory response",
  },
  {
    id: "drug-calcium-gluconate", tab: "drugs", tabLabel: "Drugs",
    section: "Drug Doses", drugId: "calcium-gluconate",
    label: "Calcium Gluconate 10% — Hypocalcaemia / HyperK",
    keywords: ["calcium gluconate", "hypocalcaemia", "hyperkalaemia", "ccb overdose", "calcium", "0.5 mL/kg"],
    description: "0.5 mL/kg of 10% IV slow (max 20 mL). 100 mg/kg for hyperK",
  },
  {
    id: "drug-calcium-chloride", tab: "drugs", tabLabel: "Drugs",
    section: "Drug Doses", drugId: "calcium-chloride",
    label: "Calcium Chloride 10% — Cardiac Arrest",
    keywords: ["calcium chloride", "cardiac arrest", "ccb", "0.2 mL/kg"],
    description: "0.2 mL/kg of 10% IV central (max 10 mL). 3× more elemental Ca than gluconate",
  },
  {
    id: "drug-magnesium", tab: "drugs", tabLabel: "Drugs",
    section: "Drug Doses", drugId: "magnesium-sulfate",
    label: "Magnesium Sulfate — Severe Asthma / Torsades",
    keywords: ["magnesium", "mgso4", "severe asthma", "torsades", "25 mg/kg", "50 mg/kg"],
    description: "25–50 mg/kg IV over 20 min (max 2 g). Monitor for hypotension",
  },
  {
    id: "drug-sodium-bicarb", tab: "drugs", tabLabel: "Drugs",
    section: "Drug Doses", drugId: "sodium-bicarb",
    label: "Sodium Bicarbonate — Metabolic Acidosis / HyperK",
    keywords: ["sodium bicarbonate", "bicarb", "metabolic acidosis", "hyperkalaemia", "tca overdose", "1 meq/kg"],
    description: "1 mEq/kg IV slow. Not routine in arrest. Dilute in neonates",
  },
  {
    id: "drug-hydrocortisone", tab: "drugs", tabLabel: "Drugs",
    section: "Drug Doses", drugId: "hydrocortisone",
    label: "Hydrocortisone — Shock / Adrenal Crisis / Asthma",
    keywords: ["hydrocortisone", "steroid", "adrenal crisis", "septic shock", "severe asthma", "2 mg/kg"],
    description: "2 mg/kg IV (max 100 mg). Adrenal crisis: 50–100 mg stat",
  },
  {
    id: "drug-ketamine-rsi", tab: "drugs", tabLabel: "Drugs",
    section: "Drug Doses", drugId: "ketamine-rsi",
    label: "Ketamine — RSI Induction",
    keywords: ["ketamine", "rsi", "rapid sequence intubation", "induction", "2 mg/kg", "shock", "asthma"],
    description: "2 mg/kg IV. Preferred in shock/asthma. Bronchodilator",
  },
  {
    id: "drug-ketamine-sedation", tab: "drugs", tabLabel: "Drugs",
    section: "Drug Doses", drugId: "ketamine-sedation",
    label: "Ketamine — Procedural Sedation",
    keywords: ["ketamine", "procedural sedation", "psa", "dissociative", "1.5 mg/kg", "im", "4 mg/kg"],
    description: "1–2 mg/kg IV or 4–5 mg/kg IM. Preserves airway. Onset 1 min IV",
  },
  {
    id: "drug-propofol", tab: "drugs", tabLabel: "Drugs",
    section: "Drug Doses", drugId: "propofol",
    label: "Propofol — RSI / Procedural Sedation",
    keywords: ["propofol", "rsi", "induction", "sedation", "2 mg/kg", "hypotension"],
    description: "2 mg/kg IV. Hypotension risk. Avoid in shock. No analgesia",
  },
  {
    id: "drug-etomidate", tab: "drugs", tabLabel: "Drugs",
    section: "Drug Doses", drugId: "etomidate",
    label: "Etomidate — RSI Haemodynamically Unstable",
    keywords: ["etomidate", "rsi", "haemodynamically unstable", "0.3 mg/kg"],
    description: "0.3 mg/kg IV. Haemodynamically neutral. Avoid in septic shock",
  },
  {
    id: "drug-midazolam-iv", tab: "drugs", tabLabel: "Drugs",
    section: "Drug Doses", drugId: "midazolam-iv",
    label: "Midazolam IV — Sedation / Status Epilepticus",
    keywords: ["midazolam", "iv", "sedation", "status epilepticus", "icu", "0.1 mg/kg", "benzo"],
    description: "0.05–0.1 mg/kg IV (max 5 mg). Reversible with flumazenil",
  },
  {
    id: "drug-midazolam-in", tab: "drugs", tabLabel: "Drugs",
    section: "Drug Doses", drugId: "midazolam-in",
    label: "Midazolam IN/Buccal — Seizure Without IV",
    keywords: ["midazolam", "intranasal", "buccal", "seizure", "no iv", "0.2 mg/kg", "in midazolam"],
    description: "0.2 mg/kg IN or buccal (max 10 mg). Onset 5–10 min",
  },
  {
    id: "drug-dexmedetomidine", tab: "drugs", tabLabel: "Drugs",
    section: "Drug Doses", drugId: "dexmedetomidine",
    label: "Dexmedetomidine — ICU Sedation / MRI",
    keywords: ["dexmedetomidine", "precedex", "icu sedation", "mri", "alpha2", "no respiratory depression"],
    description: "Load 0.5–1 mcg/kg over 10 min, then 0.2–0.7 mcg/kg/hr",
  },
  {
    id: "drug-suxamethonium", tab: "drugs", tabLabel: "Drugs",
    section: "Drug Doses", drugId: "suxamethonium",
    label: "Suxamethonium — RSI Paralysis",
    keywords: ["suxamethonium", "succinylcholine", "rsi", "paralysis", "nmb", "2 mg/kg", "depolarising"],
    description: "2 mg/kg IV. Onset 30–60 s. Contraindicated in hyperK, burns, crush injury",
  },
  {
    id: "drug-rocuronium", tab: "drugs", tabLabel: "Drugs",
    section: "Drug Doses", drugId: "rocuronium",
    label: "Rocuronium — RSI / Intubation",
    keywords: ["rocuronium", "rsi", "paralysis", "nmb", "1.2 mg/kg", "sugammadex", "non depolarising"],
    description: "1.2 mg/kg IV. Onset 60 s. Reversible with sugammadex 16 mg/kg",
  },
  {
    id: "drug-lorazepam", tab: "drugs", tabLabel: "Drugs",
    section: "Drug Doses", drugId: "lorazepam",
    label: "Lorazepam IV — Status Epilepticus First Line",
    keywords: ["lorazepam", "ativan", "status epilepticus", "seizure", "benzodiazepine", "0.1 mg/kg", "first line benzo"],
    description: "0.1 mg/kg IV (max 4 mg). First-line IV benzo for SE. Duration 12–24 hr",
  },
  {
    id: "drug-diazepam", tab: "drugs", tabLabel: "Drugs",
    section: "Drug Doses", drugId: "diazepam-iv",
    label: "Diazepam IV/PR — Status Epilepticus / Febrile Seizure",
    keywords: ["diazepam", "valium", "status epilepticus", "febrile convulsion", "rectal", "pr", "0.2 mg/kg"],
    description: "0.2 mg/kg IV or 0.5 mg/kg PR (max 10 mg). PR if no IV access",
  },
  {
    id: "drug-levetiracetam", tab: "drugs", tabLabel: "Drugs",
    section: "Drug Doses", drugId: "levetiracetam-iv",
    label: "Levetiracetam IV — Status Epilepticus 2nd Line",
    keywords: ["levetiracetam", "keppra", "levipil", "status epilepticus", "seizure", "40 mg/kg", "second line"],
    description: "40–60 mg/kg IV over 5–15 min (max 3 g). After benzos fail",
  },
  {
    id: "drug-phenytoin", tab: "drugs", tabLabel: "Drugs",
    section: "Drug Doses", drugId: "phenytoin",
    label: "Phenytoin / Fosphenytoin — Status Epilepticus",
    keywords: ["phenytoin", "fosphenytoin", "status epilepticus", "seizure", "20 mg/kg", "ecg monitoring"],
    description: "20 mg PE/kg IV (max 1500 mg). ECG monitoring mandatory",
  },
  {
    id: "drug-phenobarbital", tab: "drugs", tabLabel: "Drugs",
    section: "Drug Doses", drugId: "phenobarbital-iv",
    label: "Phenobarbital IV — Status Epilepticus 3rd Line / Neonatal",
    keywords: ["phenobarbital", "phenobarbitone", "status epilepticus", "neonatal seizures", "20 mg/kg", "third line"],
    description: "20 mg/kg IV slow (max 600 mg). Neonatal SE first line",
  },
  {
    id: "drug-valproate", tab: "drugs", tabLabel: "Drugs",
    section: "Drug Doses", drugId: "valproate-iv",
    label: "Sodium Valproate IV — Status Epilepticus",
    keywords: ["valproate", "sodium valproate", "valparin", "status epilepticus", "30 mg/kg"],
    description: "30–40 mg/kg IV over 5–10 min (max 3 g)",
  },
  {
    id: "drug-thiopentone", tab: "drugs", tabLabel: "Drugs",
    section: "Drug Doses", drugId: "thiopentone-iv",
    label: "Thiopentone — Refractory Status Epilepticus",
    keywords: ["thiopentone", "thiopental", "pentothal", "refractory status", "rse", "burst suppression"],
    description: "3–5 mg/kg IV then 1–5 mg/kg/hr. Requires intubation + EEG",
  },
  {
    id: "drug-morphine", tab: "drugs", tabLabel: "Drugs",
    section: "Drug Doses", drugId: "morphine-iv",
    label: "Morphine IV/IM — Severe Pain",
    keywords: ["morphine", "opioid", "severe pain", "0.1 mg/kg", "iv", "im"],
    description: "0.05–0.1 mg/kg IV q2–4h (max 5 mg). Have naloxone ready",
  },
  {
    id: "drug-fentanyl-iv", tab: "drugs", tabLabel: "Drugs",
    section: "Drug Doses", drugId: "fentanyl-iv",
    label: "Fentanyl IV — Procedural / Severe Pain",
    keywords: ["fentanyl", "iv", "procedural", "severe pain", "1 mcg/kg", "rsi analgesia", "chest wall rigidity"],
    description: "1–2 mcg/kg IV slow over 3–5 min (max 50 mcg)",
  },
  {
    id: "drug-fentanyl-in", tab: "drugs", tabLabel: "Drugs",
    section: "Drug Doses", drugId: "fentanyl-in",
    label: "Fentanyl IN — Acute Pain Without IV",
    keywords: ["fentanyl", "intranasal", "in", "no iv", "trauma", "1.5 mcg/kg", "atomiser"],
    description: "1.5 mcg/kg IN via atomiser (max 100 mcg). Onset 5–10 min",
  },
  {
    id: "drug-ketamine-analgesia", tab: "drugs", tabLabel: "Drugs",
    section: "Drug Doses", drugId: "ketamine-analgesia",
    label: "Ketamine Sub-dissociative — Acute Pain",
    keywords: ["ketamine", "sub dissociative", "sdk", "analgesia", "0.3 mg/kg", "opioid sparing"],
    description: "0.2–0.5 mg/kg IV over 10 min (max 30 mg). Opioid-sparing",
  },
  {
    id: "drug-ketorolac", tab: "drugs", tabLabel: "Drugs",
    section: "Drug Doses", drugId: "ketorolac-iv",
    label: "Ketorolac IV/IM — Moderate Pain / Renal Colic",
    keywords: ["ketorolac", "toradol", "nsaid", "renal colic", "0.5 mg/kg"],
    description: "0.5 mg/kg IV q6h (max 30 mg/dose). Avoid >5 days or renal impairment",
  },
  {
    id: "drug-paracetamol-iv", tab: "drugs", tabLabel: "Drugs",
    section: "Drug Doses", drugId: "paracetamol-iv",
    label: "Paracetamol IV (Perfalgan) — Pain / Fever",
    keywords: ["paracetamol", "perfalgan", "acetaminophen", "iv", "fever", "15 mg/kg"],
    description: "15 mg/kg IV over 15 min q6h (max 1 g/dose). Switch to oral ASAP",
  },
  {
    id: "drug-dopamine", tab: "drugs", tabLabel: "Drugs",
    section: "Drug Doses", drugId: "dopamine",
    label: "Dopamine Infusion — Shock",
    keywords: ["dopamine", "inotrope", "vasopressor", "shock", "2-20 mcg/kg/min"],
    description: "2–20 mcg/kg/min. Renal 2–5, β 5–10, α >10 mcg/kg/min",
  },
  {
    id: "drug-noradrenaline", tab: "drugs", tabLabel: "Drugs",
    section: "Drug Doses", drugId: "noradrenaline",
    label: "Noradrenaline Infusion — Warm Septic Shock",
    keywords: ["noradrenaline", "norepinephrine", "vasopressor", "septic shock", "warm shock"],
    description: "0.05–1 mcg/kg/min IV. First-line vasopressor in warm septic shock",
  },
  {
    id: "drug-adrenaline-infusion", tab: "drugs", tabLabel: "Drugs",
    section: "Drug Doses", drugId: "adrenaline-infusion",
    label: "Adrenaline Infusion — Cold Septic Shock",
    keywords: ["adrenaline", "epinephrine", "infusion", "cold shock", "0.05 mcg/kg/min"],
    description: "0.05–1 mcg/kg/min IV. First-line in cold shock",
  },
  {
    id: "drug-dobutamine", tab: "drugs", tabLabel: "Drugs",
    section: "Drug Doses", drugId: "dobutamine",
    label: "Dobutamine Infusion — Cardiogenic Shock",
    keywords: ["dobutamine", "inotrope", "cardiogenic shock", "heart failure"],
    description: "2–20 mcg/kg/min. β1 inotrope. Titrate to perfusion",
  },
  {
    id: "drug-milrinone", tab: "drugs", tabLabel: "Drugs",
    section: "Drug Doses", drugId: "milrinone",
    label: "Milrinone — Low CO / Post Cardiac Surgery",
    keywords: ["milrinone", "phosphodiesterase", "low cardiac output", "post cardiac surgery"],
    description: "Load 50 mcg/kg then 0.25–0.75 mcg/kg/min",
  },
  {
    id: "drug-ceftriaxone", tab: "drugs", tabLabel: "Drugs",
    section: "Drug Doses", drugId: "ceftriaxone",
    label: "Ceftriaxone IV — Sepsis / Meningitis / Enteric Fever",
    keywords: ["ceftriaxone", "rocephin", "sepsis", "meningitis", "enteric fever", "50 mg/kg", "100 mg/kg"],
    description: "Sepsis: 50 mg/kg OD. Meningitis: 100 mg/kg OD (max 4 g)",
  },
  {
    id: "drug-meropenem", tab: "drugs", tabLabel: "Drugs",
    section: "Drug Doses", drugId: "meropenem-iv",
    label: "Meropenem IV — Severe Sepsis / MDR",
    keywords: ["meropenem", "meronem", "carbapenem", "severe sepsis", "mdr", "gram negative"],
    description: "Sepsis: 20 mg/kg q8h. Meningitis: 40 mg/kg q8h (max 2 g)",
  },
  {
    id: "drug-vancomycin", tab: "drugs", tabLabel: "Drugs",
    section: "Drug Doses", drugId: "vancomycin-iv",
    label: "Vancomycin IV — MRSA / Resistant Gram-positive",
    keywords: ["vancomycin", "mrsa", "gram positive", "resistant", "15 mg/kg"],
    description: "15 mg/kg q6–8h IV over 60 min. Target trough 15–20 mcg/mL",
  },
  {
    id: "drug-gentamicin", tab: "drugs", tabLabel: "Drugs",
    section: "Drug Doses", drugId: "gentamicin",
    label: "Gentamicin IV — Gram-negative / Neonatal Sepsis",
    keywords: ["gentamicin", "aminoglycoside", "gram negative", "neonatal sepsis", "7.5 mg/kg"],
    description: "7.5 mg/kg OD IV. Neonates: 4–5 mg/kg q24–48h. Monitor levels",
  },
  {
    id: "drug-piptaz", tab: "drugs", tabLabel: "Drugs",
    section: "Drug Doses", drugId: "piptaz-iv",
    label: "Piperacillin-Tazobactam — Nosocomial / Pseudomonas",
    keywords: ["piperacillin", "tazobactam", "pip taz", "tazocin", "pseudomonas", "nosocomial", "febrile neutropenia"],
    description: "100 mg/kg q8h IV. Severe: q6h",
  },
  {
    id: "drug-acyclovir", tab: "drugs", tabLabel: "Drugs",
    section: "Drug Doses", drugId: "acyclovir-iv",
    label: "Acyclovir IV — HSV Encephalitis / Neonatal HSV",
    keywords: ["acyclovir", "zovirax", "hsv", "herpes", "encephalitis", "neonatal", "20 mg/kg"],
    description: "HSV encephalitis: 20 mg/kg q8h × 14–21 days",
  },
  {
    id: "drug-artesunate", tab: "drugs", tabLabel: "Drugs",
    section: "Drug Doses", drugId: "artesunate-iv",
    label: "Artesunate IV — Severe Falciparum Malaria",
    keywords: ["artesunate", "falcigo", "malaria", "falciparum", "severe malaria", "2.4 mg/kg"],
    description: "2.4 mg/kg at 0, 12, 24 hr then OD (min 3 days)",
  },
  {
    id: "drug-caffeine", tab: "drugs", tabLabel: "Drugs",
    section: "Drug Doses", drugId: "caffeine-citrate",
    label: "Caffeine Citrate — Apnoea of Prematurity",
    keywords: ["caffeine", "caffeine citrate", "apnoea", "prematurity", "20 mg/kg"],
    description: "Load 20 mg/kg IV/PO, maintenance 5–10 mg/kg/day",
  },
  {
    id: "drug-surfactant", tab: "drugs", tabLabel: "Drugs",
    section: "Drug Doses", drugId: "surfactant",
    label: "Surfactant — Neonatal RDS",
    keywords: ["surfactant", "poractant", "curosurf", "beractant", "survanta", "rds", "neonatal"],
    description: "Poractant 200 mg/kg ET. Beractant 100 mg/kg ET",
  },
  {
    id: "drug-pge1", tab: "drugs", tabLabel: "Drugs",
    section: "Drug Doses", drugId: "prostaglandin-e1",
    label: "Prostaglandin E1 — Duct-Dependent Heart Disease",
    keywords: ["prostaglandin", "pge1", "alprostadil", "ductus", "pda", "congenital heart"],
    description: "0.05–0.1 mcg/kg/min IV. Keep ductus open",
  },
  {
    id: "drug-dextrose", tab: "drugs", tabLabel: "Drugs",
    section: "Drug Doses", drugId: "dextrose",
    label: "Dextrose 10% — Hypoglycaemia",
    keywords: ["dextrose", "d10w", "glucose", "hypoglycaemia", "2 mL/kg"],
    description: "2 mL/kg D10W IV = 0.2 g/kg glucose",
  },
  {
    id: "drug-mannitol", tab: "drugs", tabLabel: "Drugs",
    section: "Drug Doses", drugId: "mannitol",
    label: "Mannitol 20% — Raised ICP",
    keywords: ["mannitol", "icp", "raised intracranial pressure", "tbi", "0.5 g/kg", "osmotherapy"],
    description: "0.5 g/kg IV over 20 min (= 2.5 mL/kg of 20%). Monitor osmolality",
  },
  {
    id: "drug-furosemide", tab: "drugs", tabLabel: "Drugs",
    section: "Drug Doses", drugId: "furosemide-iv",
    label: "Furosemide IV — Fluid Overload / Pulmonary Oedema",
    keywords: ["furosemide", "lasix", "frusemide", "diuretic", "fluid overload", "pulmonary oedema"],
    description: "0.5–1 mg/kg IV (max 40 mg). Monitor K⁺",
  },
  {
    id: "drug-dexamethasone-croup", tab: "drugs", tabLabel: "Drugs",
    section: "Drug Doses", drugId: "dexamethasone-croup",
    label: "Dexamethasone — Croup",
    keywords: ["dexamethasone", "croup", "stridor", "0.6 mg/kg", "laryngotracheobronchitis"],
    description: "0.6 mg/kg PO/IM/IV single dose (max 10 mg). PO as effective as IM",
  },

  // ─── DRUGS — NEBULISED ──────────────────────────────────────────────────────
  {
    id: "drugs-nebs-salbutamol", tab: "drugs", tabLabel: "Drugs",
    section: "Nebulised Drugs", drugId: "salbutamol-neb",
    label: "Salbutamol Nebulised — Asthma / Bronchospasm",
    keywords: ["salbutamol", "albuterol", "nebulised", "bronchodilator", "saba", "asthma", "bronchospasm", "asthalin", "ventolin", "2.5 mg", "5 mg"],
    description: "<20 kg: 2.5 mg · ≥20 kg: 5 mg q20min × 3. MDI+spacer preferred for mild-moderate",
  },
  {
    id: "drugs-nebs-adrenaline", tab: "drugs", tabLabel: "Drugs",
    section: "Nebulised Drugs", drugId: "adrenaline-neb",
    label: "Nebulised Adrenaline — Croup / Post-extubation Stridor",
    keywords: ["nebulised adrenaline", "neb adrenaline", "croup", "stridor", "1:1000", "0.5 mL/kg", "rebound stridor", "post extubation"],
    description: "0.5 mL/kg of 1:1000 (max 5 mL). Observe ≥2–4 hr for rebound stridor",
  },
  {
    id: "drugs-nebs-ipratropium", tab: "drugs", tabLabel: "Drugs",
    section: "Nebulised Drugs", drugId: "ipratropium-neb",
    label: "Ipratropium Bromide Nebulised — Moderate-Severe Asthma",
    keywords: ["ipratropium", "sama", "duolin", "ipravent", "moderate asthma", "severe asthma", "anticholinergic", "q20 min"],
    description: "<5 yr: 250 mcg · ≥5 yr: 500 mcg. Add to salbutamol for first 1–2 hr",
  },
  {
    id: "drugs-nebs-budesonide", tab: "drugs", tabLabel: "Drugs",
    section: "Nebulised Drugs", drugId: "budesonide-neb",
    label: "Budesonide Nebulised — Croup",
    keywords: ["budesonide", "pulmicort", "budecort", "croup", "ics", "2 mg", "subglottic oedema"],
    description: "Croup: 2 mg single dose (= 0.6 mg/kg dexamethasone PO)",
  },
  {
    id: "drugs-nebs-spacer", tab: "drugs", tabLabel: "Drugs",
    section: "Nebulised Drugs", drugId: null,
    label: "Spacer & MDI Technique by Age",
    keywords: ["spacer", "mdi", "inhaler", "aerochamber", "volumatic", "babyhaler", "mask", "mouthpiece", "technique"],
    description: "Spacer selection 0–2 yr / 2–6 yr / 6+ yr. MDI+spacer equivalent to nebuliser",
  },

  // ─── NEW ENTRIES TO ADD TO SEARCH_INDEX ────────────────────────────────────
// Add these after the existing "Nebulised Drugs" entries and before the
// "SYRUP CALCULATOR" section.
// ─────────────────────────────────────────────────────────────────────────────

  // ─── DRUGS — PER RECTAL ────────────────────────────────────────────────────
  {
    id: "drug-pr-diazepam", tab: "drugs", tabLabel: "Drugs",
    section: "Per Rectal", drugId: "diazepam-pr",
    label: "Diazepam PR — Acute Seizure / Febrile Convulsion",
    keywords: ["diazepam", "pr", "per rectal", "rectal", "seizure", "febrile convulsion", "febrile seizure", "0.5 mg/kg", "no iv", "calmpose", "valium", "rectal diazepam"],
    description: "0.5 mg/kg PR (max 10 mg). IV solution used rectally. Onset 5–10 min. Hold buttocks 1–2 min",
  },
  {
    id: "drug-pr-midazolam", tab: "drugs", tabLabel: "Drugs",
    section: "Per Rectal", drugId: "midazolam-pr",
    label: "Midazolam PR — Acute Seizure (Alternative)",
    keywords: ["midazolam", "pr", "per rectal", "rectal midazolam", "seizure", "0.4 mg/kg", "no iv", "mezolam", "dormicum", "rectal benzodiazepine"],
    description: "0.3–0.5 mg/kg PR (max 10 mg). Less preferred than rectal diazepam. Onset 5–10 min",
  },
  {
    id: "drug-pr-paraldehyde", tab: "drugs", tabLabel: "Drugs",
    section: "Per Rectal", drugId: "paraldehyde-pr",
    label: "Paraldehyde PR — Refractory Status Epilepticus",
    keywords: ["paraldehyde", "pr", "per rectal", "rectal", "refractory seizure", "status epilepticus", "0.4 mL/kg", "arachis oil", "glass syringe", "resource limited"],
    description: "0.4 mL/kg PR mixed 1:1 with arachis oil (max 8 mL). MUST use glass syringe. Onset 15–30 min",
  },
  {
    id: "drug-pr-paracetamol", tab: "drugs", tabLabel: "Drugs",
    section: "Per Rectal", drugId: "paracetamol-pr",
    label: "Paracetamol Suppository — Fever / Pain",
    keywords: ["paracetamol", "suppository", "pr", "per rectal", "fever", "pain", "vomiting", "calpol suppository", "metacin suppository", "15 mg/kg", "rectal paracetamol"],
    description: "15–20 mg/kg PR (max 1 g). Calpol suppositories 125/250/500 mg. Onset 30–60 min",
  },
  {
    id: "drug-pr-indomethacin", tab: "drugs", tabLabel: "Drugs",
    section: "Per Rectal", drugId: "indomethacin-pr",
    label: "Indomethacin Suppository — Pain / Fever",
    keywords: ["indomethacin", "indocap", "suppository", "pr", "per rectal", "nsaid", "pain", "fever", "older children"],
    description: "1.5–3 mg/kg/day PR ÷ TDS (max 50 mg/dose). Indocap-25/50 suppositories",
  },
  {
    id: "drug-pr-promethazine", tab: "drugs", tabLabel: "Drugs",
    section: "Per Rectal", drugId: "promethazine-pr",
    label: "Promethazine Suppository — Vomiting (>2 yr only)",
    keywords: ["promethazine", "phenergan", "suppository", "pr", "per rectal", "vomiting", "antiemetic", ">2 years", "0.75 mg/kg", "contraindicated infants"],
    description: "0.5–1 mg/kg PR (max 25 mg). CONTRAINDICATED <2 yr — fatal respiratory depression",
  },
  {
    id: "drug-pr-bisacodyl", tab: "drugs", tabLabel: "Drugs",
    section: "Per Rectal", drugId: "bisacodyl-pr",
    label: "Bisacodyl Suppository — Constipation",
    keywords: ["bisacodyl", "dulcolax", "suppository", "pr", "per rectal", "constipation", "laxative", "5 mg", "10 mg", "bowel preparation"],
    description: "<10 kg: 5 mg OD · ≥10 kg: 10 mg OD. Onset 15–60 min. Dulcolax widely available India",
  },
  {
    id: "drug-pr-sodium-phosphate-enema", tab: "drugs", tabLabel: "Drugs",
    section: "Per Rectal", drugId: "sodium-phosphate-enema",
    label: "Sodium Phosphate Enema — Faecal Impaction",
    keywords: ["sodium phosphate enema", "fleet enema", "relaxyl enema", "pr", "per rectal", "constipation", "faecal impaction", "bowel preparation", "2.5 mL/kg", "phosphate"],
    description: "2.5 mL/kg (max 133 mL). Relaxyl enema available India. Avoid in renal impairment",
  },

  // ─── DRUGS — INTRANASAL ────────────────────────────────────────────────────
  {
    id: "drug-in-fentanyl", tab: "drugs", tabLabel: "Drugs",
    section: "Intranasal", drugId: "fentanyl-in",
    label: "Fentanyl IN — Acute Pain Without IV Access",
    keywords: ["fentanyl", "intranasal", "in", "nasal", "acute pain", "trauma", "fracture", "1.5 mcg/kg", "mad atomiser", "no iv", "opioid nasal"],
    description: "1.5–2 mcg/kg IN via MAD (max 100 mcg). Use 100 mcg/mL. Max 0.5 mL/nostril. Onset 5–10 min",
  },
  {
    id: "drug-in-ketamine", tab: "drugs", tabLabel: "Drugs",
    section: "Intranasal", drugId: "ketamine-in",
    label: "Ketamine IN — Sub-dissociative Analgesia",
    keywords: ["ketamine", "intranasal", "in", "nasal", "sub dissociative", "analgesia", "1 mg/kg", "pre iv", "trauma pain", "mad atomiser", "50 mg/mL"],
    description: "1–2 mg/kg IN via MAD (max 75 mg). Use 50 mg/mL. Onset 5–10 min. Opioid-sparing",
  },
  {
    id: "drug-in-midazolam", tab: "drugs", tabLabel: "Drugs",
    section: "Intranasal", drugId: "midazolam-in",
    label: "Midazolam IN — Seizure / Procedural Anxiolysis",
    keywords: ["midazolam", "intranasal", "in", "nasal", "seizure", "no iv", "anxiolysis", "pre mri", "0.2 mg/kg", "mad atomiser", "5 mg/mL", "nasal burning", "mezolam"],
    description: "0.2–0.3 mg/kg IN via MAD (max 10 mg). Use 5 mg/mL undiluted. Onset 5–10 min",
  },
  {
    id: "drug-in-dexmedetomidine", tab: "drugs", tabLabel: "Drugs",
    section: "Intranasal", drugId: "dexmedetomidine-in",
    label: "Dexmedetomidine IN — MRI Sedation / Anxiolysis",
    keywords: ["dexmedetomidine", "intranasal", "in", "nasal", "mri sedation", "procedural sedation", "1 mcg/kg", "no respiratory depression", "mad atomiser", "dextomid", "precedex"],
    description: "1–2 mcg/kg IN via MAD (max 100 mcg). Onset 25–30 min. No resp depression. Ideal for MRI",
  },
  {
    id: "drug-in-naloxone", tab: "drugs", tabLabel: "Drugs",
    section: "Intranasal", drugId: "naloxone-in",
    label: "Naloxone IN — Opioid Overdose Without IV",
    keywords: ["naloxone", "intranasal", "in", "nasal", "opioid overdose", "reversal", "0.1 mg/kg", "no iv", "narcan nasal", "mad atomiser", "re narcotisation"],
    description: "0.1 mg/kg IN via MAD (max 2 mg). Use 1 mg/mL ampoule. Onset 2–5 min. May need repeat doses",
  },
  {
    id: "drug-in-diazepam", tab: "drugs", tabLabel: "Drugs",
    section: "Intranasal", drugId: "diazepam-in",
    label: "Diazepam IN — Not Preferred (Poor Bioavailability)",
    keywords: ["diazepam", "intranasal", "in", "nasal", "seizure", "poor bioavailability", "not recommended", "alternative", "0.25 mg/kg"],
    description: "NOT preferred IN — poor nasal bioavailability of Indian IV formulation. Use IN midazolam or PR diazepam instead",
  },
  {
    id: "drug-in-mupirocin", tab: "drugs", tabLabel: "Drugs",
    section: "Intranasal", drugId: "mupirocin-in",
    label: "Mupirocin 2% Nasal — MRSA Decolonisation",
    keywords: ["mupirocin", "bactroban nasal", "mupicin nasal", "mrsa", "decolonisation", "nasal ointment", "pre surgery", "bd 5 days"],
    description: "~0.5 cm each nostril BD × 5 days. MRSA decolonisation before surgery. Bactroban Nasal",
  },

  // ─── DRUGS — INTRAMUSCULAR ─────────────────────────────────────────────────
  {
    id: "drug-im-adrenaline", tab: "drugs", tabLabel: "Drugs",
    section: "Intramuscular", drugId: "adrenaline-im",
    label: "Adrenaline IM 1:1000 — Anaphylaxis First Line",
    keywords: ["adrenaline", "epinephrine", "im", "intramuscular", "anaphylaxis", "1:1000", "0.01 mg/kg", "anterolateral thigh", "epipen", "first line", "allergy"],
    description: "0.01 mg/kg IM anterolateral thigh (max 0.5 mg). Repeat q5–15 min. No absolute contraindication",
  },
  {
    id: "drug-im-midazolam", tab: "drugs", tabLabel: "Drugs",
    section: "Intramuscular", drugId: "midazolam-im",
    label: "Midazolam IM — Status Epilepticus / Pre-sedation",
    keywords: ["midazolam", "im", "intramuscular", "status epilepticus", "seizure", "0.2 mg/kg", "no iv", "rampart", "prehospital", "mezolam"],
    description: "0.2 mg/kg IM (max 10 mg). RAMPART trial: equivalent to IV lorazepam for SE. Onset 5–10 min",
  },
  {
    id: "drug-im-diazepam-not-recommended", tab: "drugs", tabLabel: "Drugs",
    section: "Intramuscular", drugId: "diazepam-im",
    label: "Diazepam IM — NOT Recommended (Erratic Absorption)",
    keywords: ["diazepam", "im", "intramuscular", "not recommended", "erratic absorption", "avoid", "use pr instead", "calmpose"],
    description: "IM diazepam NOT recommended — erratic absorption. Use PR diazepam or IM midazolam instead",
  },
  {
    id: "drug-im-ceftriaxone", tab: "drugs", tabLabel: "Drugs",
    section: "Intramuscular", drugId: "ceftriaxone-im",
    label: "Ceftriaxone IM — Sepsis / Meningitis / Enteric Fever",
    keywords: ["ceftriaxone", "im", "intramuscular", "sepsis", "meningitis", "enteric fever", "pneumonia", "50 mg/kg", "monocef", "rocephin", "lignocaine reconstitution", "outpatient"],
    description: "50 mg/kg IM OD (max 2 g). Reconstitute in 1% lignocaine. Max 1 g per site",
  },
  {
    id: "drug-im-benzylpenicillin", tab: "drugs", tabLabel: "Drugs",
    section: "Intramuscular", drugId: "benzylpenicillin-im",
    label: "Benzylpenicillin IM — Meningococcal / Pre-transfer",
    keywords: ["benzylpenicillin", "crystalline penicillin", "penicillin g", "im", "intramuscular", "meningococcal", "pre transfer", "50000 units/kg", "crystapen", "purpuric rash"],
    description: "50,000 units/kg IM stat (max 2.4 MU). Critical pre-transfer dose for suspected meningococcal disease",
  },
  {
    id: "drug-im-procaine-penicillin", tab: "drugs", tabLabel: "Drugs",
    section: "Intramuscular", drugId: "procaine-penicillin-im",
    label: "Benzathine / Procaine Penicillin IM — RF Prophylaxis",
    keywords: ["benzathine penicillin", "procaine penicillin", "penidure", "im", "intramuscular", "rheumatic fever", "prophylaxis", "1.2 mu", "600000 units", "aspirate", "hoigne syndrome", "never iv"],
    description: "<30 kg: 600,000 units · ≥30 kg: 1.2 MU IM. ALWAYS aspirate — IV injection is fatal (Hoigne syndrome)",
  },
  {
    id: "drug-im-gentamicin", tab: "drugs", tabLabel: "Drugs",
    section: "Intramuscular", drugId: "gentamicin-im",
    label: "Gentamicin IM — Gram-negative / Neonatal Sepsis",
    keywords: ["gentamicin", "im", "intramuscular", "gram negative", "neonatal sepsis", "7.5 mg/kg", "aminoglycoside", "once daily", "genticyn", "ototoxicity", "nephrotoxicity"],
    description: "7.5 mg/kg IM OD (children). Neonates: 4–5 mg/kg OD. Monitor levels if >5 days",
  },
  {
    id: "drug-im-ketorolac", tab: "drugs", tabLabel: "Drugs",
    section: "Intramuscular", drugId: "ketorolac-im",
    label: "Ketorolac IM — Moderate-Severe Pain / Renal Colic",
    keywords: ["ketorolac", "toradol", "ketanov", "im", "intramuscular", "nsaid", "pain", "renal colic", "0.5 mg/kg", "30 mg", "max 5 days"],
    description: "0.5 mg/kg IM (max 30 mg). Comparable to morphine 10 mg. Max 5 days total",
  },
  {
    id: "drug-im-ondansetron", tab: "drugs", tabLabel: "Drugs",
    section: "Intramuscular", drugId: "ondansetron-im",
    label: "Ondansetron IM — Severe Vomiting Without IV",
    keywords: ["ondansetron", "im", "intramuscular", "vomiting", "nausea", "0.1 mg/kg", "emeset", "ondem", "zofran", "off label im", "gastroenteritis"],
    description: "0.1–0.15 mg/kg IM (max 8 mg). Off-label but widely practiced India. Onset 20–30 min",
  },
  {
    id: "drug-im-dexamethasone", tab: "drugs", tabLabel: "Drugs",
    section: "Intramuscular", drugId: "dexamethasone-im",
    label: "Dexamethasone IM — Croup / Severe Allergy",
    keywords: ["dexamethasone", "im", "intramuscular", "croup", "severe allergy", "0.6 mg/kg", "dexona", "decadron", "single dose", "cerebral oedema"],
    description: "0.6 mg/kg IM (croup, max 10 mg). Single dose sufficient — duration 36–72 hr",
  },
  {
    id: "drug-im-morphine", tab: "drugs", tabLabel: "Drugs",
    section: "Intramuscular", drugId: "morphine-im",
    label: "Morphine IM — Severe Pain",
    keywords: ["morphine", "im", "intramuscular", "severe pain", "fracture", "burns", "0.1 mg/kg", "schedule x", "narcotic", "naloxone", "opioid"],
    description: "0.1–0.15 mg/kg IM (max 10 mg). Schedule X — special prescription required. Have naloxone ready",
  },
  {
    id: "drug-im-vitamin-k", tab: "drugs", tabLabel: "Drugs",
    section: "Intramuscular", drugId: "vitamin-k-im",
    label: "Vitamin K1 IM — Neonatal Prophylaxis / VKDB",
    keywords: ["vitamin k", "phytomenadione", "im", "intramuscular", "neonatal prophylaxis", "vkdb", "konakion", "1 mg", "at birth", "warfarin reversal", "haemorrhage"],
    description: "Neonates: 1 mg IM at birth (0.5 mg if <1.5 kg). Konakion MM preferred. IV bolus → anaphylaxis risk",
  },
  {
    id: "drug-im-glucagon", tab: "drugs", tabLabel: "Drugs",
    section: "Intramuscular", drugId: "glucagon-im",
    label: "Glucagon IM — Severe Hypoglycaemia Without IV",
    keywords: ["glucagon", "glucagen", "im", "intramuscular", "hypoglycaemia", "unconscious", "no iv", "0.5 mg", "1 mg", "t1dm", "glycogenolysis", "hypokit"],
    description: "<25 kg: 0.5 mg IM · ≥25 kg: 1 mg IM. GlucaGen HypoKit. Lateral position — vomiting common",
  },
  // ─── SYRUP CALCULATOR (one per drug) ──────────────────────────────────────
  {
    id: "syrup-amoxicillin", tab: "syrup", tabLabel: "Syrup Calculator",
    section: "Antibiotic", drugId: "amoxicillin-oral",
    label: "Amoxicillin Syrup",
    keywords: ["amoxicillin", "novamox", "mox", "amoxil", "syrup", "suspension", "pneumonia", "aom", "pharyngitis", "uti", "30 mg/kg"],
    description: "30 mg/kg TDS (max 500 mg). Mox-125: 25 mg/mL · Mox-250: 50 mg/mL",
  },
  {
    id: "syrup-amoxiclav", tab: "syrup", tabLabel: "Syrup Calculator",
    section: "Antibiotic", drugId: "amoxiclav-oral",
    label: "Amoxicillin-Clavulanate (Co-amoxiclav) Syrup",
    keywords: ["amoxicillin clavulanate", "co amoxiclav", "augmentin", "moxclav", "clavam", "syrup", "aom", "sinusitis", "animal bite", "45 mg/kg"],
    description: "45 mg/kg/day BD (max 875 mg). Augmentin-228 DS: 40 mg/mL",
  },
  {
    id: "syrup-cloxacillin", tab: "syrup", tabLabel: "Syrup Calculator",
    section: "Antibiotic", drugId: "cloxacillin-oral",
    label: "Cloxacillin Syrup — MSSA / Skin",
    keywords: ["cloxacillin", "klox", "bioclox", "mssa", "impetigo", "cellulitis", "empty stomach"],
    description: "25 mg/kg QID (max 500 mg). MUST give on EMPTY STOMACH",
  },
  {
    id: "syrup-cefixime", tab: "syrup", tabLabel: "Syrup Calculator",
    section: "Antibiotic", drugId: "cefixime-oral",
    label: "Cefixime Syrup",
    keywords: ["cefixime", "taxim-o", "zifi", "cefix", "topcef", "syrup", "uti", "typhoid", "aom", "8 mg/kg"],
    description: "8 mg/kg/day OD or BD (max 400 mg). Taxim-O 50: 10 mg/mL",
  },
  {
    id: "syrup-cefpodoxime", tab: "syrup", tabLabel: "Syrup Calculator",
    section: "Antibiotic", drugId: "cefpodoxime-oral",
    label: "Cefpodoxime Syrup",
    keywords: ["cefpodoxime", "cepodem", "cefoprox", "vantin", "syrup", "aom", "uti", "5 mg/kg"],
    description: "5 mg/kg BD (max 200 mg). Take WITH food",
  },
  {
    id: "syrup-cefuroxime", tab: "syrup", tabLabel: "Syrup Calculator",
    section: "Antibiotic", drugId: "cefuroxime-oral",
    label: "Cefuroxime Axetil Syrup",
    keywords: ["cefuroxime", "ceftin", "supacef", "zocef", "syrup", "aom", "pneumonia", "animal bite", "15 mg/kg"],
    description: "15 mg/kg BD (max 500 mg). MUST give with food",
  },
  {
    id: "syrup-azithromycin", tab: "syrup", tabLabel: "Syrup Calculator",
    section: "Antibiotic", drugId: "azithromycin-oral",
    label: "Azithromycin Syrup",
    keywords: ["azithromycin", "azithral", "azee", "zithromax", "syrup", "atypical", "pneumonia", "pertussis", "scrub typhus", "macrolide", "10 mg/kg"],
    description: "10 mg/kg day 1 (max 500 mg) then 5 mg/kg days 2–5",
  },
  {
    id: "syrup-azithromycin-typhoid", tab: "syrup", tabLabel: "Syrup Calculator",
    section: "Antibiotic", drugId: "azithromycin-typhoid",
    label: "Azithromycin High-Dose — Typhoid / Enteric Fever",
    keywords: ["azithromycin", "typhoid", "enteric fever", "azithral", "20 mg/kg", "high dose", "esbl salmonella"],
    description: "20 mg/kg OD × 7 days (max 1 g/day). IAP 2024 first-line for uncomplicated enteric fever",
  },
  {
    id: "syrup-clarithromycin", tab: "syrup", tabLabel: "Syrup Calculator",
    section: "Antibiotic", drugId: "clarithromycin-oral",
    label: "Clarithromycin Syrup",
    keywords: ["clarithromycin", "claribid", "klaricid", "biaxin", "syrup", "atypical pneumonia", "h pylori", "pertussis"],
    description: "7.5 mg/kg BD (max 500 mg). H. pylori triple therapy. Give with food",
  },
  {
    id: "syrup-metronidazole", tab: "syrup", tabLabel: "Syrup Calculator",
    section: "Antibiotic", drugId: "metronidazole-oral",
    label: "Metronidazole Syrup — Amoeba / Giardia",
    keywords: ["metronidazole", "flagyl", "metrogyl", "aldezole", "syrup", "amoebiasis", "giardia", "anaerobic"],
    description: "7.5 mg/kg TDS (max 400 mg). Amoebiasis: 10 mg/kg TDS × 10 days",
  },
  {
    id: "syrup-cotrimoxazole", tab: "syrup", tabLabel: "Syrup Calculator",
    section: "Antibiotic", drugId: "cotrimoxazole-oral",
    label: "Co-trimoxazole (TMP-SMX) Syrup",
    keywords: ["cotrimoxazole", "bactrim", "septran", "tmp smx", "uti", "pcp prophylaxis", "shigella"],
    description: "4–6 mg/kg TMP BD (max 160 mg TMP). PCP prophylaxis: 5 mg/kg TMP OD 3×/week",
  },
  {
    id: "syrup-isoniazid", tab: "syrup", tabLabel: "Syrup Calculator",
    section: "Antibiotic", drugId: "isoniazid-oral",
    label: "Isoniazid (INH) Syrup — TB",
    keywords: ["isoniazid", "inh", "tb", "tuberculosis", "ltbi", "10 mg/kg", "isokin"],
    description: "10 mg/kg OD (max 300 mg). LTBI: 10 mg/kg OD × 6 months. Add pyridoxine",
  },
  {
    id: "syrup-fluconazole", tab: "syrup", tabLabel: "Syrup Calculator",
    section: "Antibiotic", drugId: "fluconazole-oral",
    label: "Fluconazole Syrup — Candidiasis",
    keywords: ["fluconazole", "forcan", "syscan", "zocon", "thrush", "candida", "antifungal", "6 mg/kg"],
    description: "6–12 mg/kg OD (max 400 mg). Thrush: 3 mg/kg OD × 7 days",
  },
  {
    id: "syrup-albendazole", tab: "syrup", tabLabel: "Syrup Calculator",
    section: "Antibiotic", drugId: "albendazole-oral",
    label: "Albendazole Syrup — Helminths / Worms",
    keywords: ["albendazole", "zentel", "bandy", "noworm", "helminths", "worms", "deworming", "400 mg"],
    description: "Helminths: 400 mg single dose (>10 kg). NCC: 15 mg/kg BD × 4 weeks",
  },
  {
    id: "syrup-acyclovir-oral", tab: "syrup", tabLabel: "Syrup Calculator",
    section: "Antibiotic", drugId: "acyclovir-oral",
    label: "Acyclovir Syrup — Varicella / Herpes",
    keywords: ["acyclovir", "zovirax", "acivir", "varicella", "chickenpox", "herpes", "20 mg/kg"],
    description: "Varicella: 20 mg/kg QID × 5 days (max 800 mg/dose)",
  },
  {
    id: "syrup-chloroquine", tab: "syrup", tabLabel: "Syrup Calculator",
    section: "Antibiotic", drugId: "chloroquine-oral",
    label: "Chloroquine Syrup — P. vivax Malaria",
    keywords: ["chloroquine", "lariago", "malarex", "vivax", "malaria", "10 mg/kg"],
    description: "10 mg base/kg D1–2, then 5 mg base/kg D3. Plus primaquine for radical cure",
  },
  {
    id: "syrup-primaquine", tab: "syrup", tabLabel: "Syrup Calculator",
    section: "Antibiotic", drugId: "primaquine-oral",
    label: "Primaquine — P. vivax Radical Cure",
    keywords: ["primaquine", "vivax", "radical cure", "g6pd", "0.25 mg/kg", "malaria", "14 days"],
    description: "0.25 mg/kg OD × 14 days. G6PD screen MANDATORY before starting",
  },
  {
    id: "syrup-paracetamol", tab: "syrup", tabLabel: "Syrup Calculator",
    section: "Analgesic", drugId: "paracetamol-oral",
    label: "Paracetamol Syrup — Fever / Pain",
    keywords: ["paracetamol", "acetaminophen", "calpol", "metacin", "dolo", "syrup", "fever", "pain", "15 mg/kg"],
    description: "15 mg/kg q4–6h (max 1 g/dose). Calpol-120: 24 mg/mL · Calpol-250: 50 mg/mL",
  },
  {
    id: "syrup-ibuprofen", tab: "syrup", tabLabel: "Syrup Calculator",
    section: "Analgesic", drugId: "ibuprofen-oral",
    label: "Ibuprofen Syrup — Fever / Pain",
    keywords: ["ibuprofen", "brufen", "ibugesic", "advil", "syrup", "fever", "pain", "nsaid", "10 mg/kg"],
    description: "10 mg/kg TDS (max 400 mg). Give with food. Avoid in dengue",
  },
  {
    id: "syrup-ondansetron", tab: "syrup", tabLabel: "Syrup Calculator",
    section: "Antiemetic", drugId: "ondansetron-oral",
    label: "Ondansetron Syrup — Vomiting",
    keywords: ["ondansetron", "emeset", "ondem", "zofran", "vomikind", "syrup", "odt", "vomiting", "nausea", "0.15 mg/kg"],
    description: "0.15 mg/kg TDS (max 4 mg if <15 kg, 8 mg if ≥15 kg). ODT available",
  },
  {
    id: "syrup-domperidone", tab: "syrup", tabLabel: "Syrup Calculator",
    section: "Antiemetic", drugId: "domperidone-oral",
    label: "Domperidone Syrup — Nausea / Vomiting / GERD",
    keywords: ["domperidone", "domstal", "motilium", "vomistop", "prokinetic", "gerd", "vomiting", "0.25 mg/kg"],
    description: "0.25–0.5 mg/kg TDS before meals (max 10 mg). Short duration",
  },
  {
    id: "syrup-zinc", tab: "syrup", tabLabel: "Syrup Calculator",
    section: "ORS/Zinc", drugId: "zinc-oral",
    label: "Zinc — Diarrhoea Protocol",
    keywords: ["zinc", "diarrhoea", "ors", "oral rehydration", "20 mg", "10 mg", "zincovit", "pedizinc", "14 days"],
    description: "<6 mo: 10 mg OD · ≥6 mo: 20 mg OD × 14 days. Mandatory WHO/IAP protocol",
  },
  {
    id: "syrup-prednisolone", tab: "syrup", tabLabel: "Syrup Calculator",
    section: "Steroid", drugId: "prednisolone-oral",
    label: "Prednisolone Syrup — Asthma / Nephrotic",
    keywords: ["prednisolone", "omnacortil", "wysolone", "prelone", "syrup", "asthma", "nephrotic syndrome", "steroid", "1 mg/kg"],
    description: "Asthma: 1–2 mg/kg OD × 3–5 days. Nephrotic: 2 mg/kg OD × 6 weeks",
  },
  {
    id: "syrup-dexamethasone-oral", tab: "syrup", tabLabel: "Syrup Calculator",
    section: "Steroid", drugId: "dexamethasone-oral",
    label: "Dexamethasone Oral — Croup",
    keywords: ["dexamethasone", "croup", "dexona", "wymesone", "0.6 mg/kg", "single dose", "stridor"],
    description: "0.6 mg/kg single dose (max 10 mg). PO as effective as IM/IV for croup",
  },
  {
    id: "syrup-levetiracetam-oral", tab: "syrup", tabLabel: "Syrup Calculator",
    section: "Anticonvulsant", drugId: "levetiracetam-oral",
    label: "Levetiracetam Oral Solution — Epilepsy",
    keywords: ["levetiracetam", "keppra", "levipil", "oral solution", "seizure", "epilepsy", "10 mg/kg", "100 mg/mL"],
    description: "Start 10 mg/kg BD, increase to 30 mg/kg BD. Keppra 100 mg/mL oral solution",
  },
  {
    id: "syrup-valproate-oral", tab: "syrup", tabLabel: "Syrup Calculator",
    section: "Anticonvulsant", drugId: "valproate-oral",
    label: "Sodium Valproate Syrup — Epilepsy",
    keywords: ["valproate", "sodium valproate", "valparin", "encorate", "epilex", "syrup", "epilepsy", "absence", "10 mg/kg"],
    description: "10–15 mg/kg BD, increase to 20–40 mg/kg/day. AVOID <2 yr",
  },
  {
    id: "syrup-carbamazepine", tab: "syrup", tabLabel: "Syrup Calculator",
    section: "Anticonvulsant", drugId: "carbamazepine-oral",
    label: "Carbamazepine Syrup — Focal Epilepsy",
    keywords: ["carbamazepine", "tegretol", "mazetol", "carbatol", "syrup", "focal epilepsy", "5 mg/kg"],
    description: "Start 5 mg/kg BD, titrate to 10–20 mg/kg/day. Check HLA-B*1502 (SJS risk)",
  },
  {
    id: "syrup-phenobarbitone", tab: "syrup", tabLabel: "Syrup Calculator",
    section: "Anticonvulsant", drugId: "phenobarbitone-oral",
    label: "Phenobarbitone Syrup — Epilepsy / Neonatal",
    keywords: ["phenobarbitone", "phenobarbital", "gardenal", "luminal", "syrup", "epilepsy", "neonatal seizures", "3 mg/kg"],
    description: "3–5 mg/kg OD. First-line for neonatal seizures. Give at bedtime",
  },
  {
    id: "syrup-clobazam", tab: "syrup", tabLabel: "Syrup Calculator",
    section: "Anticonvulsant", drugId: "clobazam-oral",
    label: "Clobazam Syrup — Adjunct Epilepsy",
    keywords: ["clobazam", "frisium", "cloba", "lobazam", "lennox gastaut", "refractory epilepsy", "0.3 mg/kg"],
    description: "0.3 mg/kg BD increasing to 1 mg/kg BD. Adjunct for refractory epilepsy",
  },
  {
    id: "syrup-midazolam-oral", tab: "syrup", tabLabel: "Syrup Calculator",
    section: "Sedation", drugId: "midazolam-oral",
    label: "Midazolam Oral — Pre-procedural Sedation",
    keywords: ["midazolam", "oral", "pre medication", "procedural sedation", "0.5 mg/kg", "anxiolysis", "pre op"],
    description: "0.5 mg/kg PO 20–30 min before procedure (max 15 mg). Mix in sweet juice",
  },
  {
    id: "syrup-triclofos", tab: "syrup", tabLabel: "Syrup Calculator",
    section: "Sedation", drugId: "Triclofos Sodium",
    label: "Triclofos (Pedicloryl) — Procedural Sedation",
    keywords: ["triclofos", "pedicloryl", "chloral", "oral sedation", "mri sedation", "syrup", "sedation", "eeg", "echo", "75 mg/kg", "50 mg/kg", "pediclix", "silence", "mitflos"],
    description: "Initial 80 mg/kg PO (max 1 g). Supplement 5 mg/kg q5min from 30 min. Duration 6–8 hr",
  },
  {
    id: "syrup-hydroxyzine", tab: "syrup", tabLabel: "Syrup Calculator",
    section: "Sedation", drugId: "hydroxyzine-oral",
    label: "Hydroxyzine Syrup — Anxiolysis / Urticaria",
    keywords: ["hydroxyzine", "atarax", "vistaril", "syrup", "anxiolysis", "urticaria", "pruritus", "pre medication"],
    description: "0.5–1 mg/kg PO (max 50 mg). Also for urticaria, pruritus",
  },
  {
    id: "syrup-melatonin", tab: "syrup", tabLabel: "Syrup Calculator",
    section: "Sedation", drugId: "melatonin-oral",
    label: "Melatonin — Sleep Disorders / ASD",
    keywords: ["melatonin", "meloset", "melzap", "sleep disorder", "asd", "adhd", "insomnia", "circadian"],
    description: "Start 0.5–1 mg at bedtime; usual 1–5 mg. 30–60 min before sleep",
  },
  {
    id: "syrup-cetirizine", tab: "syrup", tabLabel: "Syrup Calculator",
    section: "Other", drugId: "cetirizine-oral",
    label: "Cetirizine Syrup — Allergic Rhinitis / Urticaria",
    keywords: ["cetirizine", "alerid", "zyrtec", "okacet", "syrup", "allergic rhinitis", "urticaria", "antihistamine"],
    description: "2–5 yr: 2.5 mg OD · 6–11 yr: 5 mg OD · ≥12 yr: 10 mg OD",
  },
  {
    id: "syrup-levocetirizine", tab: "syrup", tabLabel: "Syrup Calculator",
    section: "Other", drugId: "levocetirizine-oral",
    label: "Levocetirizine Syrup — Allergic Rhinitis",
    keywords: ["levocetirizine", "levorid", "xyzal", "levocet", "syrup", "allergic rhinitis", "urticaria"],
    description: "2–5 yr: 1.25 mg OD · 6–11 yr: 2.5 mg OD · ≥12 yr: 5 mg OD",
  },
  {
    id: "syrup-chlorpheniramine", tab: "syrup", tabLabel: "Syrup Calculator",
    section: "Other", drugId: "chlorpheniramine-oral",
    label: "Chlorpheniramine (CPM) Syrup — Allergic Rhinitis",
    keywords: ["chlorpheniramine", "cpm", "piriton", "avil", "syrup", "allergic rhinitis", "urticaria", "sedating antihistamine"],
    description: "0.1 mg/kg TDS (max 4 mg). Sedating 1st gen — avoid in infants <2 yr",
  },
  {
    id: "syrup-montelukast", tab: "syrup", tabLabel: "Syrup Calculator",
    section: "Other", drugId: "montelukast-oral",
    label: "Montelukast — Asthma Prophylaxis / Allergic Rhinitis",
    keywords: ["montelukast", "montek", "romilast", "singulair", "asthma", "allergic rhinitis", "post viral wheeze", "leukotriene"],
    description: "6–23 mo: 4 mg granules OD · 2–5 yr: 4 mg OD · 6–14 yr: 5 mg OD · ≥15 yr: 10 mg OD",
  },
  {
    id: "syrup-iron", tab: "syrup", tabLabel: "Syrup Calculator",
    section: "Other", drugId: "iron-oral",
    label: "Elemental Iron Drops/Syrup — Iron Deficiency Anaemia",
    keywords: ["iron", "elemental iron", "anaemia", "pediron", "orofer", "feronia", "3 mg/kg", "iron deficiency"],
    description: "Therapeutic: 3–6 mg/kg elemental iron OD. Take between meals",
  },
  {
    id: "syrup-vitamin-d", tab: "syrup", tabLabel: "Syrup Calculator",
    section: "Other", drugId: "vitamin-d-oral",
    label: "Vitamin D3 — Deficiency / Rickets",
    keywords: ["vitamin d", "cholecalciferol", "d3", "rickets", "deficiency", "d-rise", "uprise", "400 iu", "60000 iu"],
    description: "Prevention: 400 IU/day. Deficiency: 2000–4000 IU/day × 12 weeks",
  },
  {
    id: "syrup-ors", tab: "syrup", tabLabel: "Syrup Calculator",
    section: "Fluids / ORS", drugId: "ors-oral",
    label: "WHO-ORS — Oral Rehydration Salts",
    keywords: ["ors", "oral rehydration", "electral", "pedialyte", "diarrhoea", "dehydration", "rehydration"],
    description: "Mild: 50 mL/kg/4hr · Moderate: 100 mL/kg/4hr. Mandatory with zinc",
  },
  {
    id: "syrup-linezolid", tab: "syrup", tabLabel: "Syrup Calculator",
    section: "Antibiotic", drugId: "linezolid-oral",
    label: "Linezolid Oral — MRSA / VRE",
    keywords: ["linezolid", "lizolid", "zyvox", "mrsa", "vre", "mdr tb", "10 mg/kg", "oral bioavailability"],
    description: "<12 yr: 10 mg/kg TDS (max 600 mg). 100% oral bioavailability — switch IV early",
  },

  // ─── SEDATION & ANALGESIA TAB ──────────────────────────────────────────────
  {
    id: "sed-ketamine-psa", tab: "sedation", tabLabel: "Sedation & Analgesia",
    section: "PSA Agents", label: "Ketamine — PSA",
    keywords: ["ketamine", "psa", "procedural sedation", "dissociative", "1-2 mg/kg", "im", "4 mg/kg", "ed sedation"],
    description: "1–2 mg/kg IV or 4–5 mg/kg IM. First-line ED PSA. Bronchodilator",
  },
  {
    id: "sed-propofol-psa", tab: "sedation", tabLabel: "Sedation & Analgesia",
    section: "PSA Agents", label: "Propofol — PSA / Brief Procedures",
    keywords: ["propofol", "psa", "brief procedures", "cardioversion", "imaging", "hypotension", "apnoea"],
    description: "1–2 mg/kg IV. No analgesia. Hypotension risk. Antiemetic effect",
  },
  {
    id: "sed-midazolam-psa", tab: "sedation", tabLabel: "Sedation & Analgesia",
    section: "PSA Agents", label: "Midazolam — PSA / Anxiolysis",
    keywords: ["midazolam", "psa", "anxiolysis", "0.05 mg/kg", "in midazolam", "buccal", "flumazenil"],
    description: "0.05–0.1 mg/kg IV · 0.2 mg/kg IN · 0.3 mg/kg buccal. Reversible",
  },
  {
    id: "sed-fentanyl-psa", tab: "sedation", tabLabel: "Sedation & Analgesia",
    section: "PSA Agents", label: "Fentanyl — Analgesia / PSA",
    keywords: ["fentanyl", "psa", "analgesia", "1 mcg/kg", "in fentanyl", "chest wall rigidity", "naloxone"],
    description: "1–2 mcg/kg IV slow · 1.5 mcg/kg IN. Rapid analgesia. Reversible with naloxone",
  },
  {
    id: "sed-ketofol", tab: "sedation", tabLabel: "Sedation & Analgesia",
    section: "PSA Agents", label: "Ketofol — Combined Sedation",
    keywords: ["ketofol", "ketamine propofol", "1:1", "combination sedation", "psa"],
    description: "0.5–1 mg/kg of 1:1 mixture IV. Balances haemodynamics and emergence",
  },
  {
    id: "sed-dexmedetomidine-psa", tab: "sedation", tabLabel: "Sedation & Analgesia",
    section: "PSA Agents", label: "Dexmedetomidine — MRI / ICU / No Resp Depression",
    keywords: ["dexmedetomidine", "mri sedation", "icu sedation", "alpha2", "no respiratory depression", "brady", "precedex"],
    description: "Load 0.5–1 mcg/kg over 10 min, then 0.2–0.7 mcg/kg/hr. No resp depression",
  },
  {
    id: "sed-nitrous", tab: "sedation", tabLabel: "Sedation & Analgesia",
    section: "PSA Agents", label: "Nitrous Oxide 50:50 — Minor Procedures",
    keywords: ["nitrous oxide", "entonox", "n2o", "self administered", "procedural", "iv cannula", "dressing"],
    description: "Self-administered inhalation. ≥5 yr cooperative. Offset in 5 min",
  },
  {
    id: "sed-etomidate-psa", tab: "sedation", tabLabel: "Sedation & Analgesia",
    section: "PSA Agents", label: "Etomidate — RSI Haemodynamically Unstable",
    keywords: ["etomidate", "rsi", "haemodynamically unstable", "0.3 mg/kg", "myoclonus"],
    description: "0.3 mg/kg IV. Haemodynamically neutral RSI induction",
  },
  {
    id: "sed-triclofos-sedation", tab: "sedation", tabLabel: "Sedation & Analgesia",
    section: "Oral Sedation", label: "Triclofos — Oral Sedation MRI/EEG",
    keywords: ["triclofos", "pedicloryl", "oral sedation", "mri sedation", "eeg", "echo", "50 mg/kg", "75 mg/kg"],
    description: "50–75 mg/kg PO (max 1000 mg). Onset 20–40 min. Duration 6–8 hr",
  },
  {
    id: "sed-midazolam-oral-sedation", tab: "sedation", tabLabel: "Sedation & Analgesia",
    section: "Oral Sedation", label: "Midazolam Oral — Pre-procedural",
    keywords: ["midazolam oral", "oral pre med", "0.5 mg/kg", "anxiolysis", "premedication", "juice"],
    description: "0.3–0.6 mg/kg PO (max 15 mg) 20–30 min before procedure",
  },
  {
    id: "sed-dex-intranasal", tab: "sedation", tabLabel: "Sedation & Analgesia",
    section: "Oral Sedation", label: "Dexmedetomidine Intranasal — MRI Pre-med",
    keywords: ["dexmedetomidine intranasal", "in dex", "mri premedication", "1-2 mcg/kg", "no respiratory depression", "mad"],
    description: "1–2 mcg/kg IN with MAD atomiser. Onset 30 min. Ideal for MRI, ECHO",
  },
  {
    id: "sed-local-anaesthetics", tab: "sedation", tabLabel: "Sedation & Analgesia",
    section: "Local Anaesthetics", label: "Local Anaesthetic Safe Doses",
    keywords: ["local anaesthetic", "lignocaine", "lidocaine", "bupivacaine", "max dose", "toxicity", "last", "4.5 mg/kg", "2 mg/kg"],
    description: "Lignocaine max 4.5 mg/kg plain · Bupivacaine max 2 mg/kg. Never with epi for digits",
  },
  {
    id: "sed-nerve-blocks", tab: "sedation", tabLabel: "Sedation & Analgesia",
    section: "Nerve Blocks", label: "Paediatric Nerve Blocks — FANSB / Digital / IITB",
    keywords: ["nerve block", "fascia iliaca", "femoral", "digital block", "intercostal", "scalp block", "wound infiltration", "ultrasound"],
    description: "FANSB, digital, fascia iliaca, intercostal. Aspirate q5 mL. Monitor for LAST",
  },
  {
    id: "sed-last", tab: "sedation", tabLabel: "Sedation & Analgesia",
    section: "LAST", label: "LAST — Local Anaesthetic Systemic Toxicity",
    keywords: ["last", "local anaesthetic toxicity", "intralipid", "20% lipid emulsion", "cardiac arrest la", "seizure la", "tinnitus", "1.5 mL/kg"],
    description: "Intralipid 20%: 1.5 mL/kg bolus + 0.25–0.5 mL/kg/min infusion. Max 12 mL/kg",
  },
  {
    id: "sed-psa-principles", tab: "sedation", tabLabel: "Sedation & Analgesia",
    section: "PSA Principles", label: "PSA Pre / During / Post Procedure",
    keywords: ["psa principles", "pre procedure", "monitoring", "fasting", "npo", "discharge criteria", "post procedure"],
    description: "Pre: NPO, consent, monitoring setup. During: airway watch. Post: discharge criteria",
  },

  // ─── NEONATAL ──────────────────────────────────────────────────────────────
  {
    id: "neo-nrp", tab: "neonatal", tabLabel: "Neonatal",
    section: "NRP", label: "Neonatal Resuscitation (NRP 2020)",
    keywords: ["nrp", "neonatal resuscitation", "ppv", "positive pressure ventilation", "t-piece", "hr check", "delayed cord clamping", "delivery room"],
    description: "Delayed cord clamping ≥60 s · Initial FiO₂ 0.21 term · HR <60 → CPR 3:1",
  },
  {
    id: "neo-doses", tab: "neonatal", tabLabel: "Neonatal",
    section: "Doses", label: "Neonatal Drug Doses — Adrenaline / ETT / UVC",
    keywords: ["neonatal dose", "ett depth neonate", "uvc", "umbilical venous catheter", "adrenaline neonate", "phenobarbital neonate", "caffeine neonate"],
    description: "Adrenaline 0.01–0.03 mg/kg · ETT depth (6+wt) cm · UVC (1.5×wt+5.5) cm",
  },
  {
    id: "neo-apgar", tab: "neonatal", tabLabel: "Neonatal",
    section: "APGAR", label: "APGAR Score",
    keywords: ["apgar", "score", "newborn assessment", "tone", "grimace", "colour", "1 minute", "5 minutes"],
    description: "APGAR at 1 & 5 min. Score ≥7 normal · 4–6 moderate · <4 severe",
  },
  {
    id: "neo-stops", tab: "neonatal", tabLabel: "Neonatal",
    section: "STOPS", label: "STOPS — Neonatal Mortality Score",
    keywords: ["stops", "neonatal mortality", "prognosis", "sensorium", "temperature", "oxygenation", "perfusion", "sugar", "nicu score"],
    description: "STOPS score (0–10). Score >2 predicts mortality ~83%",
  },
  {
    id: "neo-vitals", tab: "neonatal", tabLabel: "Neonatal",
    section: "Vitals", label: "Neonatal Normal Vitals & SpO₂ Targets",
    keywords: ["neonatal vitals", "normal neonate", "neonatal heart rate", "neonatal rr", "spo2 targets nrp", "preductal", "postductal"],
    description: "HR 100–160, RR 40–60, SpO₂ targets: 1 min 60–65% → 10 min 85–95%",
  },
  {
    id: "neo-spo2-targets", tab: "neonatal", tabLabel: "Neonatal",
    section: "NRP", label: "Preductal SpO₂ Targets NRP",
    keywords: ["spo2 targets", "preductal", "nrp", "fio2", "right hand", "delivery room", "1 minute", "10 minute"],
    description: "1 min: 60–65% · 3 min: 70–75% · 5 min: 80–85% · 10 min: 85–95%",
  },

  // ─── TRAUMA ────────────────────────────────────────────────────────────────
  {
    id: "trauma-primary", tab: "trauma", tabLabel: "Trauma Resuscitation",
    section: "Primary Survey", label: "xABCDE Primary Survey — ATLS 2025",
    keywords: ["primary survey", "xabcde", "atls", "haemorrhage control", "tourniquet", "airway trauma", "c-spine", "mils", "tension pneumothorax", "fast"],
    description: "x = Exsanguinating haemorrhage first. ABCDE with simultaneous intervention",
  },
  {
    id: "trauma-shock", tab: "trauma", tabLabel: "Trauma Resuscitation",
    section: "Shock & Fluids", label: "Haemorrhagic Shock Classification",
    keywords: ["haemorrhagic shock", "class I II III IV", "blood loss", "ebv", "permissive hypotension", "blood products", "damage control", "mtp"],
    description: "Class I–IV. Blood products 1:1:1. Permissive hypotension until surgical control",
  },
  {
    id: "trauma-txa", tab: "trauma", tabLabel: "Trauma Resuscitation",
    section: "Shock & Fluids", label: "Tranexamic Acid (TXA) — Within 3 Hours",
    keywords: ["txa", "tranexamic acid", "15 mg/kg", "major haemorrhage", "trauma bleeding", "within 3 hours", "antifibrinolytic"],
    description: "TXA 15 mg/kg (max 1 g) IV over 10 min, then 2 mg/kg/hr × 8 hr. <3 hr",
  },
  {
    id: "trauma-tbi", tab: "trauma", tabLabel: "Trauma Resuscitation",
    section: "TBI", label: "TBI — GCS / ICP Management",
    keywords: ["tbi", "traumatic brain injury", "gcs", "intracranial pressure", "icp", "mannitol", "hypertonic saline", "herniation", "cushing triad"],
    description: "GCS ≤8 = severe. Osmotherapy: 3% NaCl 2–5 mL/kg or Mannitol 0.5 g/kg",
  },
  {
    id: "trauma-pecarn", tab: "trauma", tabLabel: "Trauma Resuscitation",
    section: "TBI", label: "PECARN CT Rule — Head Injury",
    keywords: ["pecarn", "head injury", "ct head", "citbi", "gcs 14", "scalp haematoma", "loss of consciousness", "basilar skull", "raccoon eyes"],
    description: "<2 yr: GCS ≤14, AMS, skull #, non-frontal haematoma. ≥2 yr: GCS ≤14, AMS, basilar #",
  },

  // ─── ALGORITHMS ────────────────────────────────────────────────────────────
  {
    id: "algo-septic-shock", tab: "algorithms", tabLabel: "Management Algorithms",
    section: "ED Management", label: "Septic Shock Algorithm",
    keywords: ["septic shock", "sepsis", "hour 1 bundle", "fluid bolus", "antibiotics", "norepinephrine", "lactate", "warm shock", "cold shock"],
    description: "Hour-1: 20 mL/kg bolus, cultures, antibiotics <1 hr, noradrenaline if fluid-refractory",
  },
  {
    id: "algo-anaphylaxis", tab: "algorithms", tabLabel: "Management Algorithms",
    section: "ED Management", label: "Anaphylaxis Algorithm",
    keywords: ["anaphylaxis", "adrenaline im", "epinephrine", "anterolateral thigh", "biphasic", "epipen", "allergy", "urticaria"],
    description: "Epi IM 0.01 mg/kg (max 0.5 mg) anterolateral thigh — ONLY life-saving drug. Repeat q5–15 min",
  },
  {
    id: "algo-dka", tab: "algorithms", tabLabel: "Management Algorithms",
    section: "ED Management", label: "DKA Algorithm",
    keywords: ["dka", "diabetic ketoacidosis", "insulin", "cerebral oedema", "deficit 48 hours", "0.9% ns", "ispad", "iap dka"],
    description: "Deficit over 48 hr · Insulin after 1 hr fluids · Cerebral oedema: mannitol or 3% NaCl",
  },
  {
    id: "algo-status-epilepticus", tab: "algorithms", tabLabel: "Management Algorithms",
    section: "ED Management", label: "Status Epilepticus Algorithm",
    keywords: ["status epilepticus", "seizure", "midazolam in", "lorazepam", "levetiracetam", "phenytoin", "refractory", "iap 2021"],
    description: "0–5 min: midazolam IN · 5–20 min: lorazepam/LEV · 20–40 min: midazolam infusion",
  },
  {
    id: "algo-meningitis", tab: "algorithms", tabLabel: "Management Algorithms",
    section: "ED Management", label: "Bacterial Meningitis Algorithm",
    keywords: ["meningitis", "ceftriaxone", "dexamethasone", "csf", "lp", "bacterial", "iap 2019"],
    description: "Ceftriaxone 100 mg/kg + dexamethasone before/with 1st dose. LP if no raised ICP signs",
  },
  {
    id: "algo-asthma", tab: "algorithms", tabLabel: "Management Algorithms",
    section: "ED Management", label: "Acute Asthma Algorithm",
    keywords: ["asthma", "salbutamol", "ipratropium", "magnesium", "prednisolone", "dexamethasone", "severity", "silent chest"],
    description: "Salbutamol MDI q20min × 3 + systemic steroids. MgSO₄ for severe. IV salbut for critical",
  },
  {
    id: "algo-croup", tab: "algorithms", tabLabel: "Management Algorithms",
    section: "ED Management", label: "Croup Algorithm",
    keywords: ["croup", "dexamethasone", "nebulised adrenaline", "westley score", "stridor", "ltb", "barking cough"],
    description: "Dexamethasone 0.6 mg/kg PO all grades. Neb adrenaline for mod-severe. Obs 2–4 hr",
  },
  {
    id: "algo-dengue", tab: "algorithms", tabLabel: "Management Algorithms",
    section: "ED Management", label: "Dengue Algorithm",
    keywords: ["dengue", "group a b c", "ns1", "plasma leakage", "haematocrit", "platelets", "warning signs", "dss"],
    description: "Group A outpatient · Group B IV fluids · Group C resuscitation. No NSAIDs/steroids",
  },
  {
    id: "algo-aha", tab: "algorithms", tabLabel: "Management Algorithms",
    section: "AHA Algorithms", label: "AHA PALS 2025 Algorithms",
    keywords: ["pals", "aha", "2025", "cardiac arrest", "cpr", "shockable", "non shockable", "defibrillation", "rosc"],
    description: "Updated 2025 AHA PALS: CPR cadence, defibrillation, post-arrest care",
  },
  {
    id: "algo-guidelines", tab: "algorithms", tabLabel: "Management Algorithms",
    section: "Clinical Guidelines", label: "IAP Clinical Guidelines 2019–2024",
    keywords: ["iap guidelines", "indian academy pediatrics", "asthma iap", "bronchiolitis iap", "sepsis iap", "dka iap", "dengue iap", "meningitis iap"],
    description: "IAP 2019–2024 key points for asthma, bronchiolitis, croup, SE, sepsis, DKA, dengue",
  },
  {
    id: "algo-pathways", tab: "algorithms", tabLabel: "Management Algorithms",
    section: "Interactive Pathways", label: "Interactive Decision-Tree Pathways",
    keywords: ["pathway", "decision tree", "interactive", "asthma severity", "dehydration pathway", "febrile seizure", "bronchiolitis pathway", "care plan", "pdf"],
    description: "Click-through pathways with weight-based doses at endpoint. Export care plan PDF",
  },
  {
    id: "algo-differentials", tab: "algorithms", tabLabel: "Management Algorithms",
    section: "Differentials", label: "Differential Diagnosis — Wheeze, Stridor, Altered Consciousness",
    keywords: ["differential diagnosis", "ddx", "wheeze", "stridor", "altered consciousness", "rash", "abdominal pain", "limp", "red flags"],
    description: "Diagnosis tables by chief complaint with age, clues, workup, red flags",
  },

  // ─── PREHOSPITAL ───────────────────────────────────────────────────────────
  {
    id: "preh-triage", tab: "prehospital", tabLabel: "Prehospital",
    section: "Triage", label: "Prehospital Triage — AVPU & ABCDE",
    keywords: ["triage", "avpu", "alert", "voice", "pain", "unresponsive", "abcde prehospital", "prem"],
    description: "AVPU scale. PREM triangle: ABCDE rapid assessment with simultaneous intervention",
  },
  {
    id: "preh-bls", tab: "prehospital", tabLabel: "Prehospital",
    section: "BLS & CPR", label: "Basic Life Support & CPR",
    keywords: ["bls", "basic life support", "cpr", "rescue breathing", "chest compressions", "15:2"],
    description: "Check responsiveness, 2 rescue breaths, 15:2 CPR. Adrenaline q3–5 min IV/IO",
  },
  {
    id: "preh-choking", tab: "prehospital", tabLabel: "Prehospital",
    section: "Choking", label: "Choking — Heimlich / Back Blows",
    keywords: ["choking", "heimlich", "back blows", "chest thrusts", "foreign body airway", "infant choking"],
    description: "Child ≥1 yr: 5 abdominal thrusts. Infant <1 yr: 5 back blows + 5 chest thrusts",
  },
  {
    id: "preh-seizure", tab: "prehospital", tabLabel: "Prehospital",
    section: "Seizures", label: "Seizure First Aid — Midazolam IN/IM",
    keywords: ["seizure prehospital", "convulsion", "midazolam prehospital", "in midazolam", "febrile seizure", "recovery position"],
    description: "Recovery position, O₂, midazolam 0.2 mg/kg IM/IN/buccal",
  },
  {
    id: "preh-poison", tab: "prehospital", tabLabel: "Prehospital",
    section: "Poisoning", label: "Poisoning — Activated Charcoal & Antidotes",
    keywords: ["poisoning", "activated charcoal", "naloxone", "atropine organophosphate", "co poisoning", "corrosive", "antidote"],
    description: "Activated charcoal within 2 hr. CO → O₂. OP → atropine. Never induce vomiting",
  },
  {
    id: "preh-poison-centres", tab: "prehospital", tabLabel: "Prehospital",
    section: "Poison Centres", label: "Poison Information Centres India — 24 hr",
    keywords: ["poison centre", "poison control", "aiims poison", "1800-425-1213", "antidote guidance", "poison helpline"],
    description: "AIIMS: 011-26850691 · CMC Vellore: 1800-425-1213 (toll-free) · Amrita Kochi: 484-2858056",
  },
  {
    id: "preh-snakebite", tab: "prehospital", tabLabel: "Prehospital",
    section: "Envenomation", label: "Snake Bite — RIGHT Mnemonic / Scorpion Prazosin",
    keywords: ["snake bite", "right mnemonic", "asv", "antivenom", "tourniquet snake", "scorpion", "prazosin", "envenomation"],
    description: "Snake: Reassure · Immobilise · Get to hospital · Tell doctor. Scorpion: prazosin 30 mcg/kg",
  },
  {
    id: "preh-burns", tab: "prehospital", tabLabel: "Prehospital",
    section: "Burns", label: "Burns First Aid — Cool Running Water 20 min",
    keywords: ["burns first aid", "cool water", "tbsa estimation", "inhalation injury", "facial burns", "stridor burns"],
    description: "Cool running water 20 min within 30 min. No ice. Inhalation injury → early intubation",
  },

  // ─── IMMUNISATION ──────────────────────────────────────────────────────────
  {
    id: "imm-iap", tab: "immunisation", tabLabel: "Immunisation",
    section: "IAP Schedule", label: "IAP-ACVIP 2023 Immunisation Schedule",
    keywords: ["iap schedule", "immunisation", "vaccine", "acvip 2023", "dtap", "ipv", "pcv", "rotavirus", "mmr", "varicella", "hpv", "typhoid tcv"],
    description: "Complete IAP-ACVIP 2023 schedule from birth to 18 yr. HPV for boys new 2023",
  },
  {
    id: "imm-uip", tab: "immunisation", tabLabel: "Immunisation",
    section: "NIP/UIP Schedule", label: "National Immunisation Programme (NIP/UIP) — GoI",
    keywords: ["uip", "nip", "government schedule", "bcg", "opv", "hbv", "pentavalent", "fipv", "mr", "je", "vitamin a", "td", "free vaccine"],
    description: "GoI/NHM free vaccination: BCG, OPV, Pentavalent, fIPV, Rotavirus, PCV, MR, JE, Td",
  },
  {
    id: "imm-hpv", tab: "immunisation", tabLabel: "Immunisation",
    section: "IAP Schedule", label: "HPV Vaccine — Girls & Boys (ACVIP 2023 NEW)",
    keywords: ["hpv", "human papillomavirus", "gardasil", "9vhpv", "girls", "boys", "9-14 years", "2 dose", "cervical cancer", "acvip 2023"],
    description: "9–14 yr girls AND boys: 2-dose schedule (0 and 6 months). 9vHPV preferred. NEW 2023",
  },
  {
    id: "imm-typhoid-tcv", tab: "immunisation", tabLabel: "Immunisation",
    section: "IAP Schedule", label: "Typhoid Conjugate Vaccine (TCV)",
    keywords: ["typhoid", "tcv", "typbar", "typhibev", "conjugate", "9 months", "enteric fever", "salmonella"],
    description: "Single dose IM from 9 months. TCV superior to Vi-PS. Booster optional at 2 yr",
  },
  {
    id: "imm-rabies-pep", tab: "immunisation", tabLabel: "Immunisation",
    section: "Special Vaccines", label: "Rabies PEP — Post-Exposure Prophylaxis",
    keywords: ["rabies pep", "post exposure prophylaxis", "rig", "rabies immunoglobulin", "animal bite", "5 dose essen", "thai red cross", "id intradermal"],
    description: "PCEC/PVRV: 5-dose Essen IM or 4-visit Thai Red Cross ID. RIG 20 IU/kg wound infiltration D0",
  },
  {
    id: "imm-catch-up", tab: "immunisation", tabLabel: "Immunisation",
    section: "Catch-up", label: "Catch-Up Vaccination Principles",
    keywords: ["catch up vaccine", "missed vaccine", "delayed vaccine", "never restart", "minimum interval", "same visit", "partial immunisation"],
    description: "Never restart a series. Give all due vaccines same visit. Respect minimum intervals",
  },
  {
    id: "imm-nnf-sepsis", tab: "immunisation", tabLabel: "Immunisation",
    section: "National Guidelines", label: "NNF — Neonatal Sepsis Guidelines",
    keywords: ["nnf", "neonatal sepsis", "eos", "los", "early onset sepsis", "ampicillin gentamicin", "pip tazo", "blood culture"],
    description: "EOS: Ampicillin + Gentamicin. LONS: Pip-Tazo or Clox + Amikacin. Culture before antibiotics",
  },
  {
    id: "imm-nnf-rop", tab: "immunisation", tabLabel: "Immunisation",
    section: "National Guidelines", label: "NNF — ROP Screening (Retinopathy of Prematurity)",
    keywords: ["rop", "retinopathy prematurity", "screening", "1750 g", "34 weeks", "laser", "anti vegf", "type 1 rop"],
    description: "Screen ≤1750 g or ≤34 wk. First exam: 4 weeks after birth or 32 weeks PMA",
  },
  {
    id: "imm-ntep", tab: "immunisation", tabLabel: "Immunisation",
    section: "National Guidelines", label: "NTEP — Paediatric TB Guidelines 2022",
    keywords: ["tb", "tuberculosis", "ntep", "rntcp", "isoniazid", "rifampicin", "pyrazinamide", "fdc", "akurit", "nikshay", "ltbi", "mantoux", "mdr tb"],
    description: "2HRZE/4HR with weight-based FDC. LTBI: INH 10 mg/kg × 6 months. NIKSHAY mandatory",
  },
  {
    id: "imm-nvbdcp-malaria", tab: "immunisation", tabLabel: "Immunisation",
    section: "National Guidelines", label: "NVBDCP — Malaria Guidelines 2023",
    keywords: ["malaria", "nvbdcp", "plasmodium vivax", "plasmodium falciparum", "artemether lumefantrine", "chloroquine", "artesunate iv", "primaquine", "g6pd"],
    description: "P. vivax: Chloroquine + Primaquine 14d. P. falciparum: AL/Coartem. Severe: IV Artesunate",
  },
  {
    id: "imm-nvbdcp-dengue", tab: "immunisation", tabLabel: "Immunisation",
    section: "National Guidelines", label: "NVBDCP — Dengue Guidelines 2021",
    keywords: ["dengue", "nvbdcp", "ns1", "igm dengue", "group b dengue", "dengue platelet", "warning signs"],
    description: "Group A/B/C fluid management. Platelets only <10,000 or active bleeding. No NSAIDs",
  },
  {
    id: "imm-sam", tab: "immunisation", tabLabel: "Immunisation",
    section: "National Guidelines", label: "SAM — Severe Acute Malnutrition Management",
    keywords: ["sam", "severe acute malnutrition", "muac", "rutf", "plumpy nut", "f-75", "f-100", "hypoglycaemia sam", "avoid bolus sam", "cmam"],
    description: "SAM: MUAC <11.5 cm. Avoid IV bolus. F-75→F-100. Glucose q2–3h. Amoxicillin prophylaxis",
  },
  {
    id: "imm-ams", tab: "immunisation", tabLabel: "Immunisation",
    section: "National Guidelines", label: "NCDC Antimicrobial Stewardship (AWaRe India 2023)",
    keywords: ["antimicrobial stewardship", "aware", "access watch reserve", "esbl", "de-escalate", "carbapenem", "colistin", "last resort"],
    description: "Access first-line · Watch: restricted · Reserve: XDR/PDR only. De-escalate 48–72 hr",
  },

  // ─── CO-PILOT ──────────────────────────────────────────────────────────────
  {
    id: "copilot-main", tab: "copilot", tabLabel: "Co-Pilot",
    section: "AI Assistant", label: "Co-Pilot — AI Clinical Assistant",
    keywords: ["copilot", "ai", "assistant", "clinical support", "ask", "chat", "question"],
    description: "AI-powered clinical assistant for paediatric emergency queries",
  },
];
